### ISSUE TITLE
[ldapadmin] Update passwd message includes internal URL link

### ISSUE THREAD

**Issue by hsquividant** [georchestra/georchestra#1080]
###### 

[GeoSAS] Update your password

Dear umrsas test,

You (or someone else) asked to reset your password on http://geowww.agrocampus-ouest.fr/.
If you did not request any password update, just ignore this e-mail, you're safe.

To set a new password for your user (utest), go to http://localhost:8180/ldapadmin/account/newPassword?token=ea386d98-88ac-408e-b273-74d541d69b37.
You will then be able to connect to the platform.

Caution: this e-mail is personal, don't forward it.

---

Sent by GeoSAS (http://geowww.agrocampus-ouest.fr/)
######

**Comment by fvanderbiest** [comment]
En effet, voir le thread https://groups.google.com/forum/#!topic/georchestra-dev/qTsYt9CZ4Qs

Nous devons adapter la documentation sur ce point.

**Comment by fvanderbiest** [comment]
En fait, la doc est déjà correcte  ... voir https://github.com/georchestra/georchestra/blob/15.06/doc/setup/tomcat.md#configure-connector

Donc je ferme.

**Comment by fvanderbiest** [comment]
Reopening, since the doc is one thing, but fixing the issue is another one ;-)

From the apache documentation:

```ProxyPreserveHost On```
"When enabled, this option will pass the Host: line from the incoming request to the proxied host, instead of the hostname specified in the ProxyPass line.

Might be what we're looking for ?
