### ISSUE TITLE
PENDING_USERS : rename

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1107]
Renaming is required so that PENDING is not considered as a prefix.

**Comment by pmauduit** [comment]
SV_PENDING ?

**Comment by fvanderbiest** [comment]
Maybe SV_PENDINGUSERS or just PENDINGUSERS, yes.

**Comment by fvanderbiest** [comment]
All merged

**Comment by fvanderbiest** [comment]
@landryb makes me think (IRC) that the underscore char might not be the best one to split hierarchies.

Proposals:
 * EL__COMCOM_DU_PAYS_TRUC
 * EL_COMCOM-DU-PAYS-TRUC
 * EL/COMCOM-DU-PAYS-TRUC

**Comment by landryb** [comment]
See the geoserver workspaces on pigma's instance, _ is also used directly in workspaces names, and i think people are used to _ to separate 'words'.

So either we change (sorry!) for / (seems natural?) or double underscore as a hierarchy separator, or we leave the code as is and document that people should use - as 'word separator' in group names. @fphg, any insight on this ?

**Comment by fphg** [comment]
didn't catch the point

There shall be no such thing as word separator in group names. ie in "EL_something", "something" is a non-significant ID.

**Comment by fvanderbiest** [comment]
> There shall be no such thing as word separator in group names. ie in "EL_something", "something" is a non-significant ID.

Sorry, I don't get you. In ```EL_DDAF80``` the DDAF80 part is significant...
You don't like EL_COMCOM-DU-PAYS-TRUC ?

**Comment by fphg** [comment]
I'd like EL_COMCOM-DU-PAYS, EL_1234567 or EL_COMCOM_DU_PAYS... Anything beyond EL_ shall be OK

**Comment by fvanderbiest** [comment]
```EL_COMCOM_DU_PAYS``` won't be possible anymore for those who'll be using the new admin console (see Rennes' CCTP)

**Comment by fphg** [comment]
:(
Does this intend to reflect a hierarchical organization ?

**Comment by fvanderbiest** [comment]
> Does this intend to reflect a hierarchical organization ?

yes, typically EL_RM_SERVICE1_SOUSSERVICE2

**Comment by fphg** [comment]
RM requirement; guess geob won't use this. Cf "COMMUNAUTE DE COMMUNE PAIMPOL-GOELO".

**Comment by landryb** [comment]
Yes, but now you cant do this anymore( or things will be shown as sub-trees in ldapadmin), since _ is now a hierarchy separator.

**Comment by fphg** [comment]
As long as other app do not rely on this specific behavior, i've got no opinion. If users want subtrees-based group names they may use the module, if they don't they can use some other ldap tool.

Something disturbs me. Ldapadmin also provides user services : account creation, change password. ldapadmin is somewhat mandatory for a geOrchestra deploy.

**Comment by fvanderbiest** [comment]
ldapadmin will still be provided, unchanged.

This is a new app, providing new capabilities (I thought you were aware of it, see this thread https://groups.google.com/forum/#!topic/georchestra-dev/bjDwkBho1Aw ), but relying on (eventually new) ldapadmin services.

This is the way I currently see it, so that the maintenance tasks are not doubled.

**Comment by landryb** [comment]
Well i havent used ldapadmin so far here because ldap users/passwords are handled in drupal, i only see ldapadmin as a tool to quickly browse in groups/users and only do this.

I hadnt understood either that this was for a new webapp... but imo, the 'hierarchical groups' feature (and all the ACL handling that come with it) will be only used by power admins/platforms, so the 'regular users' shouldnt be impacted too much by the feature. The issue is, if they start building their georchestra instance using only ldapadmin, doing their own flat groups using NAME_WITH_UNDERSCORE (because it feels 'natural') and later on they realize they want a more powerful ACL handling and start looking at the new webapp, they're screwed and have to rename all their groups. Hence... instead of now specialcasing the single underscore, maybe we should use a separator ppl wouldnt naturally use.

Using / as a separator looks a recipe for disaster since quickly looking at LDIF specs (https://www.ietf.org/rfc/rfc2849.txt), it has to be escaped, and madness ensues. double underscore or dash or + or = sign, dunno.. apparently, one can also uses spaces in a dn, but i wouldnt :) - either way, as long as it's documented.....

**Comment by fphg** [comment]
OK
Sorry didn't react to the last post on the ML.
Didn't approve the (single) tree structure either :)

Use case : members of a public structure EL_CC-ABC automatically shall be members of EL_AUTHPUB (ABC is a public authority), EL_CC (ABC is a local administration) and EL_ADHERENT (ABC attending to SDI). They will receive subsequent layer autorisations.

Can't reasonably use EL_ADHERENT_AUTHPUB_CC_CC-ABC, and rename it to EL_AUTHPUB_CC_CC-ABC if ABC resign.

@landryb +1 on not using /
regexp A-Za-z0-9_- ?

**Comment by fvanderbiest** [comment]
> Can't reasonably use EL_ADHERENT_AUTHPUB_CC_CC-ABC, and rename it to EL_AUTHPUB_CC_CC-ABC if ABC resign.

That's the reason why we're keeping ldapadmin unchanged, for those who don't want hierarchical groups.

The drawback is that they won't be able to benefit from the shiny new webapp.
One solution would be to have a configuration flag for this new webapp, which would let the admin choose between flat and complex, tree-like, hierarchies. Not sure this is feasable for the same amount though ...
