### ISSUE TITLE
Mapfishapp - Link a SLD file when you add a shapefile

### ISSUE THREAD

**Issue by lvinsonneau** [georchestra/georchestra#1160]
In Mapfish, when you add a layer from local file, you can add in a zipfile coming from a shapefile.
We could think it would be possible to add a SLD file in the zipfile in order to have the good style in the viewer, but it seams to be not possible.
Is there a technic reason ?
Is it hard to code ?

**Comment by landryb** [comment]
The geoserver REST API allows to POST sld files, so technically it's possible.

**Comment by fvanderbiest** [comment]
Uploaded shapefiles are added to the map as an OpenLayers Vector layer, so we would need to convert the SLD to an OpenLayers Style object. This can be done pretty easily IMO.

**Comment by lvinsonneau** [comment]
Thanks for your clear explanations. So, I just have to find a good developer ;-)...
You know if it is an expected use case ? 
I know that someone can think it couldn't be good because it can incite in the wrong direction not to put the data in ogc services, but I think it's also a good way for test or temporary data.

**Comment by pmauduit** [comment]
Technically "mapfishapp-side", it would require some changes somewhere around this entry point:
https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/UpLoadGeoFileController.java#L316

Since for now, the webservice takes a file then returns data as GeoJSON, it would require to find a way to also get the style along the response. But relying on http://gis.stackexchange.com/questions/22474/geojson-styling-information it does not seem to be easy to bundle the style infos into the GeoJSON without implementing our own private extensions.

So maybe we should for such a development provide another webservice where the user could store its own styles and select the one it wants on the uploaded layer.

**Comment by fvanderbiest** [comment]
> Since for now, the webservice takes a file then returns data as GeoJSON, it would require to find a way to also get the style along with the response.

Our service could return something like this:
```json
{
    "geojson": {...},
    "style": "sld_string"
}
```
And the sld string would then be parsed client-side.
