### ISSUE TITLE
2 users with the same email address ?

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1316]
is it possible to set the same email address to different users, in georchestra LDAP ?
it seems that it is possible when using the ldapmodify command line, but it appears that only one is visible when using georchestra GUI. why this limitation ?
my 2 users are pseudo-users of georchestra, and they are using the same service email address.
so, i would like to use, with the ansible terminology, the following ldif files : 
1 : dn: uid={{ georchestra.user.open.name }},ou=users,{{ openldap.basedn }}
mail: {{ openldap_adminemail }}
uid: {{ georchestra.user.open.name }}
2 : dn: uid={{ georchestra.user.rsct.name }},ou=users,{{ openldap.basedn }}
mail: {{ openldap_adminemail }}
uid: {{ georchestra.user.rsct.name }}
do you think it is possible ?

**Comment by Vampouille** [comment]
Email should be unique :
https://github.com/georchestra/georchestra/blob/15.12/ldapadmin/src/main/java/org/georchestra/ldapadmin/ds/AccountDaoImpl.java#L138

If you can create 2 users with same email in ldap, you will not be able to modify those users according to : 
https://github.com/georchestra/georchestra/blob/15.12/ldapadmin/src/main/java/org/georchestra/ldapadmin/ds/AccountDaoImpl.java#L244

Additionally, you will not be able to search users by email :
https://github.com/georchestra/georchestra/blob/15.12/ldapadmin/src/main/java/org/georchestra/ldapadmin/ds/AccountDaoImpl.java#L398
This webservices will only return first user with specified email

**Comment by fvanderbiest** [comment]
> is it possible to set the same email address to different users, in georchestra LDAP ?

Use the + sign, eg me+test1@provider.com and me+test2@provider.com are equivalent.

**Comment by pmauduit** [comment]
> Use the + sign, eg me+test1@provider.com and me+test2@provider.com are equivalent.

Only equivalent if the mail system from "provider.com" supports it ;-)

**Comment by MaxiReglisse** [comment]
ok, thanks for your answers. i will try the solution with the sign "+".
a remark : if the mail user is unique, it could be used as login, isn't it ?

**Comment by pmauduit** [comment]
Right but you will have to change several spring-security related configuration files (using the datadir, but if you are still using the "config.jar configuration mechanism", it should be pretty similar):

- https://github.com/georchestra/datadir/blob/15.12/cas/cas.properties#L25
- https://github.com/georchestra/datadir/blob/15.12/security-proxy/security-proxy.properties#L21

This has not been tested though, it might be more complicated than that from the CAS-configuration side, because it would require to lookup the correct LDAP entry for the user using 'email: <mail>' (instead of trying to bind onto the LDAP as it is done for now), to actually have a hand onto the 'uid=...,dc=users,...', but I'm pretty sure that spring-security has addressed this use-case.
