### ISSUE TITLE
GeoNetwork 3 - datadir is mandatory

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1334]
GN3 datadir is currently mandatory, ie the config jar created from the template repository is not applied.
This is not an ideal situation because it requires more documentation, and might confuse users.

Currently, to deploy a GN3 on 15.12, people have to: 
- clone https://github.com/georchestra/datadir somewhere (eg `/srv/tomcat/georchestra/work/datadir/`)
- configure their tomcat hosting GN3 with:

```
-Dgeonetwork.dir=/srv/tomcat/georchestra/work/gn_data
-Dgeonetwork.jeeves.configuration.overrides.file=/srv/tomcat/georchestra/work/datadir/geonetwork/config/config-overrides-georchestra.xml
```
- finally edit all the files in `/srv/tomcat/georchestra/work/datadir/geonetwork` and replace:
  - `geonetwork.dir=/tmp/gn_data` --> `geonetwork.dir=/srv/tomcat/georchestra/work/gn_data`
  - `${georchestra.datadir}` --> `/srv/tomcat/georchestra/work/datadir/`
  - `ldap.security.credentials` et al. in `geonetwork.properties`

**Comment by pmauduit** [comment]
I thought we did agree this week on the following: config.jar should not be considered as configuration purposes, only code modifications / webapp customizations, datadir should. The main reason that the config.jar is not applied IMHO on gn3 is because no one ordered customizations onto it yet. It could be the case in the future.

So yes, the datadir is kind of mandatory here, but I'm not in fond of duplicating the related files into geonetwork (duplication, what we are trying to avoid elsewhere). From my PoV, documenting it and pointing the users willing to use gn3 without datadir-mode is ok. Or yet another maven leg-work to `git clone` the datadir and include the necessary files to the webapp (along with the `sed s/datadir/srv/tomcat/whatever/` ? :(

**Comment by fvanderbiest** [comment]
OK, not an issue anymore, except for those who'd like to override CSS / HTML files.
