### ISSUE TITLE
Georchestra Docker behind proxy

### ISSUE THREAD

**Issue by matteocitron** [georchestra/georchestra#1386]
hello, 
I have a instance georchestra latest deploy with rancher.
But the host is behind a http proxy. 
How can I tell geOrchestra my credentials for the http proxy ?

Thks

**Comment by fvanderbiest** [comment]
I think we do not support proxies at the moment with docker.
Would not be too hard I guess.

You could try with `-Dhttp.proxyHost=...` & `-Dhttp.proxyPort=...` in the image CMD, eg https://github.com/georchestra/georchestra/blob/15.12/security-proxy/src/docker/Dockerfile#L7

**Comment by matteocitron** [comment]
Yes , i try this way on another instance. thanks for your answer.

**Comment by fvanderbiest** [comment]
Raising priority, since we have another same report recently ...

**Comment by fvanderbiest** [comment]
Well, most of the job should be done, since https://github.com/georchestra/georchestra/commit/d785abce7367273dde42b928b81cfa9c68fcf6fe allowed these settings via the JAVA_OPTIONS env var.

Editing the docker-compose.yml file, setting `JAVA_OPTIONS = -Dhttp.proxyHost=... -Dhttp.proxyPort=...` at least for the security-proxy (but also for GeoServer, GeoNetwork & Extractorapp) should work.

Please report any issues.
