### ISSUE TITLE
LDAP groups become roles

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1415]
This makes more sense in the light of future changes ("organizations" will be the new LDAP "groups")

**Comment by fvanderbiest** [comment]
Am I missing something here ? Maybe ansible...

**Comment by landryb** [comment]
If you want to do ansible right, you should ... actually provide the migration tasks renaming the ou :p

**Comment by fvanderbiest** [comment]
Well, I'll leave it to you then ;-)

**Comment by landryb** [comment]
There are two aspects to consider:
  * handling new installs: `git grep ou=groups` shows where it has to be replaced, other than that since the openldap role in the playbook fetches ldif files from the master branch, the creation of the DIT itself should just work
  * handling migration of existing installs: checking if `ou=groups` exists in the DIT, and rename it to `ou=roles`

**Comment by fvanderbiest** [comment]
And since this is just the beginning of LDAP changes on master, there's no urge IMO ...

**Comment by fvanderbiest** [comment]
If no one objects on these 4 PRs, they'll be merged next Monday:
 * https://github.com/georchestra/template/pull/27
 * https://github.com/georchestra/geoserver_minimal_datadir/pull/2
 * https://github.com/georchestra/datadir/pull/18
 * https://github.com/georchestra/georchestra/pull/1416

**Comment by fvanderbiest** [comment]
All done !
