### ISSUE TITLE
Remove the need for a config jar

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1417]
... except for client-side overrides.

Eg: currently, having a config jar is to my knowledge the only way to customize the header image...

**Comment by pmauduit** [comment]
The main issue with config.jar is that it can erase versioned files, since it basically follows the current workflow:

1. the config.jar is generated
2. copied into ~/.m2 repository
3. on each webapps which requires it, it is unpacked into <module>/target/
4. maven then copies <module>/target/generated-config/... onto <module>src/ 

Erasing files into src is not a good practice, and is even dangerous (if someone git add / commit / push sensitive informations).

If we remove the config.jar, we would need to find another way to override / add java sources though.

**Comment by fvanderbiest** [comment]
> If we remove the config.jar, we would need to find another way to override / add java sources though.

I'm not sure we really need to override java sources.

**Comment by pmauduit** [comment]
> I'm not sure we really need to override java sources.

If we do, the config.jar is not a way (in term of maven / java sources management) to do it correctly.

**Comment by fvanderbiest** [comment]
First step is https://github.com/georchestra/template/pull/30 (not to be merged for now)

**Comment by fvanderbiest** [comment]
Second step happens gradually in branch https://github.com/georchestra/georchestra/tree/datadir-only

**Comment by fvanderbiest** [comment]
This won't make it for 16.12 unfortunately.

**Comment by fvanderbiest** [comment]
Apps:
- [ ] console
- [ ] mapfishapp
- [ ] extractorapp
- [ ] analytics
- [ ] atlas
- [ ] cas
- [ ] geonetwork
- [ ] geoserver
- [ ] geowebcache
- [ ] header
- [ ] proxy

**Comment by severo** [comment]
@fvanderbiest shouldn't https://github.com/georchestra/georchestra/tree/datadir-only branch be deleted?

**Comment by severo** [comment]
I understand the idea of this issue, and I approve it, mainly because it's a lot simpler to understand for the users that will install and configure an instance. But it's important to note that we lose one of the properties: avoiding the redundancy. See https://github.com/georchestra/georchestra/tree/master/config:

> (...) The second problem is that many projects have shared configuration parameters like database urls.
> 
> There are two parts that are designed to overcome these problems:
> 
>  - The shared.maven.filters properties file in the root config directory is a file called shared.maven.filters. This file contains the parameters that are shared between many projects. The file contains the default values and when the configuration jar is being built; all text files with @propertyName@ will be replaced with the property in shared.maven.filters based on propertyName.

Should we do something? Or is it a drawback that we assume?

**Comment by fvanderbiest** [comment]
> But it's important to note that we lose one of the properties: avoiding the redundancy

Not exactly, see https://github.com/georchestra/georchestra/issues/1922#issuecomment-370455239 and https://github.com/georchestra/georchestra/issues/2068

**Comment by fvanderbiest** [comment]
> @fvanderbiest shouldn't https://github.com/georchestra/georchestra/tree/datadir-only branch be deleted?

right

**Comment by severo** [comment]
I realize that some of the files that we are now ignoring will need to be versioned now (see https://github.com/georchestra/georchestra/pull/2285/files). So, part of the work on this issue is to check the .gitignore files to ensure we are not ignoring important files.

**Comment by severo** [comment]
It's very hard to have the ideas very clear, because there are a lot of different cases:

- the configuration depends on the module
- the order priority order may be different
- some existing files are never used (see https://github.com/georchestra/datadir/issues/90)
- the documentation is outdated.

In order to follow with the work, I will create a small documentation file for every module that explains how the configuration works, and how the defaults can be overridden (it will be more a reference list of properties and files, with the priority order, than a tutorial or a course - the objective is to give a reference to the developers and to avoid the confusion).

**Comment by severo** [comment]
For gwc, see #2334, #2335, #2336.

**Comment by fvanderbiest** [comment]
#2345 to put the nail in the coffin (hopefully)

**Comment by landryb** [comment]
there's still #2210 no ?
