### ISSUE TITLE
Docker deployment - login url

### ISSUE THREAD

**Issue by Merry31** [georchestra/georchestra#1443]
Hi, 
I tried to deploy the geochestra stack with a rancher plaform of 2 hosts. The containers seems to run correctly. But when i go to the home page and i click to login, i am redirect to : 
http://localhost:8080/cas/login?service=http%3A%2F%2Flocalhost%3A8080%2Fj_spring_cas_security_check

Is this related to the conf maven.filter ? 

Thank you

Julien

**Comment by pmauduit** [comment]
It seems that the default docker configuration does not fit your environment, you should adapt it to your needs, modifying the following files in the underlying containers: /etc/georchestra/security-proxy/security-proxy.properties in the SP container:

https://github.com/georchestra/datadir/blob/docker-15.12/security-proxy/security-proxy.properties#L2-L14 

The default configuration files used in the official docker images are meant to suit a local development deploy. Some of the possible ways to fix the issue is to use a named volume on /etc/georchestra to make your moduifications persistent.

**Comment by Merry31** [comment]
Ok thank you for your answer.
