### ISSUE TITLE
mapfish-print-config java option

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1527]
Mapfishapp print requires `-Dmapfish-print-config=/etc/georchestra/mapfishapp/print/config.yaml` which is a bit redundant with `-Dgeorchestra.datadir=/etc/georchestra` eg https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/docker/Dockerfile#L20
It's also error prone (it's easy to forget it)

Is there a way to prevent this ?

**Comment by pmauduit** [comment]
The problem is that mapfishapp and mapfish-printv2 are not the same servlet:

https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/WEB-INF/web.xml#L36-L43

And web.xml does not allow us to be "conditional" (e.g. "if georchestra.datadir is defined, then ... else ...", which is possible in spring xml configs though).
