### ISSUE TITLE
mapfishapp - graphic scale in bottom bar is 30 % wrong

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1535]
Some users reports this issue :

![screenshot316](https://cloud.githubusercontent.com/assets/6370443/19681372/70e9039e-9aa9-11e6-840b-f7013edb879c.png)

**Comment by Gaetanbru** [comment]
Hello, we may be could propose a solution : 

In the GEOR.mappanel.js file, the geodesic option is set to false (line 127) like that : 
        var scaleOptions = {
        		geodesic : false,
        		div:div        
        };
        map.addControl(new OpenLayers.Control.ScaleLine(scaleOptions));

This type of measure is generaly use to calculate geodesic measures instead of planar measures.

However, to be consistent it's possible to change the calcule of length in addon 'Measure'. It's possible to change around line 365 : 
    geometry.getGeodesicLength() by geometry.getLength()

With this modifications, if you measure scale line we find the same result.

**Comment by fvanderbiest** [comment]
Right, we miss the geodesic option.

**Comment by MaelREBOUX** [comment]
To confirm but based on the experience of these users, the measures at high scale (< 1/500) are good in a tolerance of 5% on our 10 cm orthophotography.

This example : 7,30 m in reality.
![screenshot319](https://cloud.githubusercontent.com/assets/6370443/19716389/d6527a28-9b5b-11e6-871d-d28f04745858.png)

So I would prefer to keep the actual method wich seems very good.

**Comment by fvanderbiest** [comment]
> So we understand that we have to test with geodesic : true ?

Just redeploy your viewer & it should be good now.

**Comment by MaelREBOUX** [comment]
Oups : comment written without refresh the page. OK I'll test.
