### ISSUE TITLE
[Mapfishapp] Random position for addon's icons

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#1567]
Since I installed Georchestra, I noticed that my addon's icons are randomly placed in the mapfishapp's toolbar.

Their positions can vary at each loading/refresh of the page.

I found that come from the loading order of the addons, because the position set in the "target" option is relative to the already loaded addons.

Example : 

I have a streetview addon with "tbar_11", a cadastrapp addon with "tbar_12" and a quicksearch addon with "tbar_13".

If the quicksearch addon is the first loaded an added to the toolbar, his position will be after the "Help" menu, because the other addons are not yet inserted so the index 13 is not the one we want at this moment.

For this configuration to work, we need to have the good loading order : streetview, cadastrapp and quicksearch.

But actually it look that there is no fixed order for addons to load, so we can't be sure to have the good index in the "target" config.

**Comment by landryb** [comment]
Fwiw, this issue is still present in 18.06, and annoying when you have several addons in the toolbar. I briefly looked at the extjs code that loads the addon and couldnt figure out what influenced the loading order. 

The doc in https://github.com/georchestra/georchestra/tree/master/mapfishapp/src/main/webapp/app/addons#addon-placement shows that all addons use the `this.target.insertButton(this.position` construct, - and the code in `fetchAndLoadTools` seem to iterate on the result of `ws/addons` reply.. for which the order should be constant ?

**Comment by fvanderbiest** [comment]
IIRC it's network-bound :-(

**Comment by landryb** [comment]
oh so first come-first loaded when fetching the `manifest.json` files ? that explains the random... fun one!
