### ISSUE TITLE
EMailProxy documentation missing

### ISSUE THREAD

**Issue by Vampouille** [georchestra/georchestra#1576]
We need to add documentation about new email proxy service. This webservice is limited to 'ROLE_MOD_EMAILPROXY' role that does not exists.

**Comment by fvanderbiest** [comment]
Right, service introduced with https://github.com/georchestra/georchestra/pull/1572 (minimal doc inside)

By default, `ROLE_MOD_EMAILPROXY` does not exist, which is great, since no one will be able to use it by default (not kidding, since this service is relatively specific). Those who would like to enable it will have to either create `ROLE_MOD_EMAILPROXY` and tag users with it **or** replace `ROLE_MOD_EMAILPROXY` with (eg) `ROLE_USER` in /etc/georchestra/security-proxy/security-mappings.xml (eg https://github.com/georchestra/datadir/blob/master/security-proxy/security-mappings.xml)

**Comment by fvanderbiest** [comment]
Done with https://github.com/georchestra/datadir/commit/d68df780964e87a7331e6481576bcc9ed447772a
