### ISSUE TITLE
[geoserver] update to latest stable geoserver (2.12.1)

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1655]
I tried to update geoserver (without geofence) in branch https://github.com/georchestra/georchestra/tree/geoserver_2.10.x

Not much was needed to build it (2deb5500f999bd2a81d9a3ac9be9082fdf31a7f3), and it starts, but ...

 * https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/js/jquery.inline-info.js and https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/js/jquery-1.2.6.min.js which are loaded in every page end up as 404
 * the UserGroupRoleServicesPage displays a stacktrace Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: org.geoserver.security.ldap.config.LDAPUserGroupServiceConfig
 * it's impossible to create a new workspace: instead of saving it and returning to the ws list, the page loads again, with an empty form.
 * probably other unspotted glitches too ...

**Comment by landryb** [comment]
Dupe with #1482 ?

**Comment by fvanderbiest** [comment]
> Dupe with #1482 ?

right !

**Comment by pmauduit** [comment]
> https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/js/jquery.inline-info.js and https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/js/jquery-1.2.6.min.js which are loaded in every page end up as 404

Not GS-side, that is actually "our fault", due to config.jar:
https://github.com/georchestra/georchestra/blob/16.12/config/defaults/geoserver-webapp/WEB-INF/classes/org/geoserver/web/GeoServerBasePage.html#L16-L17

My proposition (having in mind that we want to get rid of the config.jar mecanism): remove the dependency on it on the geoserver-webapp/pom.xml, then integrate the special file directly into geoserver-webapp.

**Comment by pmauduit** [comment]
Trying to integrate the previous file GeoServerBasePage.html, there are currently some properties that have to be resolved at compile time (`@propertiesName@`). It is possible to resolve them at runtime using georchestra-commons but this would require to fork the GS web-core module.

**Comment by fvanderbiest** [comment]
Only `shared.instance.name` and `shared.header.height` in https://github.com/georchestra/georchestra/blob/16.12/config/defaults/geoserver-webapp/WEB-INF/classes/org/geoserver/web/GeoServerBasePage.html, yes.

Maybe we can forget about them at first.

**Comment by pmauduit** [comment]
Current status

> https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/js/jquery.inline-info.js and https://georchestra.mydomain.org/geoserver/web/wicket/bookmarkable/js/jquery-1.2.6.min.js which are loaded in every page end up as 404

Due to a very old GeoServerBasePage.html integrated with the config.jar, the 2 js files are not sourced anymore in newer versions of GS.

> the UserGroupRoleServicesPage displays a stacktrace Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: org.geoserver.security.ldap.config.LDAPUserGroupServiceConfig

Niel's PR to manage user/roles are not exactly in the same Java package, see working branch for the datadir here: https://github.com/georchestra/geoserver_minimal_datadir/tree/gs-2.12.1

> it's impossible to create a new workspace: instead of saving it and returning to the ws list, the page loads again, with an empty form.

Problem is not on GS side, but on the SP, I don't know yet which parameter (cookie ? http header ?) is lost, but faking headers and hitting directly onto GS works.

> probably other unspotted glitches too ...

I guess the main challenge now is to fix the previous point.

**Comment by pmauduit** [comment]
Status:

My branch seems to work fine into a jetty, but the behavior is slightly broken when using tomcat:

* URLs are encoded instead of being transmitted "as is", so an extra decoding is necessary into the SP (see https://github.com/georchestra/georchestra/commit/25910bb0567c252802dfad1e923f360af5bdcc18). Decoding an already-decoded URL does not harm Jetty, so I propose to always decode the URL.
* Wicket is lost when constructing redirect URLs, probably also due to some different assumptions when implementing the servlet specs in jetty vs tomcat.

**Comment by pmauduit** [comment]
> Wicket is lost when constructing redirect URLs, probably also due to some different assumptions when implementing the servlet specs in jetty vs tomcat.

In case of 301/302 redirects, The HTTP spec seems to settle that the `Location` http header should be absolute, but as of tomcat 7.x (?), it is now allowed to send a relative Location header. One way to solve the issue in Tomcat is to forbid relative locations (even if the browsers do not seem to be bothered by the relative/absolute aspects of the URL).

Forbidding relative urls can be done by editing the context.xml tomcat file, and add the following:

```xml
<Context  useRelativeRedirects="false">
[...]
```

After that, the deploy on sandbox.g.o seems ok (just an error on the about page, but which seems to come from upstream - utests are also broken).
