### ISSUE TITLE
gn3 - requires map widget activated to display the "view data" button which links to mapfishapp

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1696]
GN3 currently requires the map widget to be activated (from /geonetwork/srv/fre/admin.console#/settings), for the "view data" link to be shown in the metadata.

![screenshot from 2017-03-24 11-37-13](https://cloud.githubusercontent.com/assets/265319/24290707/3f792a98-1086-11e7-9169-1a3db28d912f.png)

![screenshot from 2017-03-24 11-38-02](https://cloud.githubusercontent.com/assets/265319/24290728/5cbb6454-1086-11e7-8e87-5d0338ba8335.png)

Admins should have the ability to enable these buttons regardless of the viewer, be it the internal one, or an external one, such as mapfishapp.

**Comment by fvanderbiest** [comment]
See also #1165

**Comment by fvanderbiest** [comment]
isMapViewerEnabled set to true by default with https://github.com/georchestra/geonetwork/commit/c67f66520931dad92bd2e2c85093849f2146d32f 

Now, trying to hide the "map viewer" tab.

**Comment by fvanderbiest** [comment]
> Now, trying to hide the "map viewer" tab.

See https://github.com/georchestra/geonetwork/commit/af1e246ab4455e30ea6eb526bf33db1810dc3d92

**Comment by landryb** [comment]
Sorry but i think this is done the wrong way... This is again (like with 2.11) going in the direction of *forking* geonetwork (thus making it harder to merge new versions) instead of properly pushing back changes there for having things configurable. What if the administrator wants the GN3 map viewer tab for whatever reasons ? But maybe this is all reworked/different in 3.4 and it will have to be redone differently...

I know lack of resources/time and all, but that's sad.

**Comment by fvanderbiest** [comment]
GN 3.4 will be in 18.06, hopefully with a better integration.
