### ISSUE TITLE
geonetwork - header switch into english langage

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra#1756]
Since spring 2016 when you switch from one module of geOrchestra like GeoServer or Mapfishapp to GeoNetwork, the header is constantly switching into english langage.

We can see that on the CRAIG instance https://ids.craig.fr/geocat/ 

![screenshot793](https://user-images.githubusercontent.com/6370443/28015760-be16459e-6571-11e7-8591-93321af763ab.png)

![screenshot794](https://user-images.githubusercontent.com/6370443/28015761-c09d06e0-6571-11e7-87a9-9fef0ae1bc37.png)

**Comment by MaelREBOUX** [comment]
Any idea @landryb ?

**Comment by landryb** [comment]
default should be controlled by language in header.properties, and is overriden by lang= in th url. Maybe its overriden by a webapp, then propagated to others. no idea. Probably geonetwork messing things up.

**Comment by fvanderbiest** [comment]
https://ids.craig.fr/geocat/ calls an iframe with https://ids.craig.fr/header/?active=geonetwork&lang=en ... which explains the behavior.

But this is surprising, since the code in 16.12 does not load `/header/?active=geonetwork&lang=en` but `/header/?active=geonetwork`, see https://github.com/georchestra/geonetwork/blob/georchestra-gn3-16.12/web/src/main/webapp/xslt/base-layout.xsl#L47

**Comment by fvanderbiest** [comment]
Do you witness this on other platforms ?

**Comment by fvanderbiest** [comment]
Got it, https://github.com/georchestra/geonetwork/commit/9336abd308f2e868701169a4761737fae5fa0055 fixes the issue since last july ...
