### ISSUE TITLE
Point releases

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1761]
I'd like to introduce [point releases](https://en.wikipedia.org/wiki/Point_release) in geOrchestra, implemented with tags such as `16.12.1`, `16.12.2` and so on.  
This would yield a better readability of the bugfixes that are backported to stable branches.

We would still have annual releases (implemented with branches), introducing new features.

Opinions ?

**Comment by pmauduit** [comment]
+1

**Comment by fphg** [comment]
+1

to me, a reccuring problem is that you can't guess the version of a running app from the browser

**Comment by fvanderbiest** [comment]
> to me, a reccuring problem is that you can't guess the version of a running app from the browser

Well, the current proposal won't help for this.

**Comment by MaelREBOUX** [comment]
I am agree for this system of release.

It important to be able to say to a customer that an issue exists in 16.12.x release and have been fixed in 16.12.x release.
We also could "_garantee_" than a particular functionnality works fine in a the release A and have a regression in the release B. That is better for communication.

For that point a good system is the WordPress plugin site. Example : https://wordpress.org/plugins/akismet/
The idea : say that a add-on has been approved by users / mainteners for A, B and C releases of geOrchestra but not for D.


> > to me, a reccuring problem is that you can't guess the version of a running app from the browser

> Well, the current proposal won't help for this.

Other issue but linked to this one. Must open an other issue to discuss on how to show that. On a dashboard ?

**Comment by fvanderbiest** [comment]
Done from 20.0.0 on
https://github.com/georchestra/georchestra/releases
