### ISSUE TITLE
Module 'ngNewRouter' is not available in ldapadmin

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#1780]
as you can see on https://georchestra-mshe.univ-fcomte.fr/ldapadmin/console/, with the usual login/password, ldapadmin doesn't display any users.
with page inspection, one can see the two following errors:

```
Uncaught ReferenceError: jQuery is not defined
    at libraries.js:6
    at libraries.js:6
```

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module admin_console due to:
Error: [$injector:modulerr] Failed to instantiate module ngNewRouter due to:
Error: [$injector:nomod] Module 'ngNewRouter' is not available!
```
thanks in advance for your help.

**Comment by pmauduit** [comment]
loading the url you provided, it seems that the libraries.js is not correct, it works on sandbox.georchestra.org but the size of the js file differs (~ 1.2M, where in the latest docker image it takes only 276K). This is likely a CI / compilation issue.

**Comment by Vampouille** [comment]
@MaxiReglisse How did you build ldapadmin webapp ?

**Comment by MaxiReglisse** [comment]
i did not build ldapadmin, i am using docker-compose. ldapadmin is the latest : 
georchestra/ldapadmin        latest              e49fd19ad8f2        8 days ago          319MB

**Comment by pmauduit** [comment]
@MaxiReglisse nothing changed from our side (except trying to see what was wrong in the Jenkins build workspace), but since some commits on master branch, another build has been launched on the CI. 

Analyzing the new latest docker image for ldapadmin, the libraries.js file is now 1.3MB big. Can you please `docker pull` and retry to see if you still have the same issue ?

**Comment by davinciagf** [comment]
Same issue with the last docker images.
Console log:

> Error: [$injector:modulerr] Failed to instantiate module admin_console due to:
[$injector:modulerr] Failed to instantiate module angularUtils.directives.dirPagination due to:
[$injector:nomod] Module 'angularUtils.directives.dirPagination' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.0-rc.1/$injector/nomod?p0=angularUtils.directives.dirPagination
r/<@https://georchestra.spacebel.be/ldapadmin/console/public/libraries.js:3:28733
yt/</</<@https://georchestra.spacebel.be/ldapadmin/console/public/libraries.js:4:6950
e@https://georchestra.spacebel.be/ldapadmin/console/public/libraries.js:4:6423
yt/</<@https://georchestra.spacebel.be/ldapadmin/console/public/libraries.js:4:6735
d/<@https://georchestra.spacebel.be/ldapadmin/console/public/libraries.js:4:15739
o@https://georchestra.spacebel.be/ldapadmin/console/public/libraries.js:3:29179
d@ht

**Comment by MaxiReglisse** [comment]
the problem seems to be solved with the latest ldapadmin image.
georchestra/ldapadmin        latest              fbce72bc7916        4 days ago          584MB
thanks !!!

**Comment by fvanderbiest** [comment]
Good news. Thanks Ernest.

**Comment by MaxiReglisse** [comment]
hey !! it does not work anymore !
the image before 16h30 was OK, but the  last has the same problem : 
Uncaught ReferenceError: jQuery is not defined

    at libraries.js:6
    at libraries.js:6
libraries.js:1 Uncaught Error: [$injector:modulerr] Failed to instantiate module admin_console due to:
Error: [$injector:modulerr] Failed to instantiate module ngNewRouter due to:
Error: [$injector:nomod] Module 'ngNewRouter' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.0-rc.1/$injector/nomod?p0=ngNewRouter

**Comment by pmauduit** [comment]
Could you please retry with latest image published today ? There has been a build this afternoon, and I cannot reproduce with the default docker composition.

```
latest 270 MB an hour ago
```

Anyway, this is hard to keep track of the different versions published on docker-hub, we might want to customize the tag to be able to detect potential regressions (but, well, since we are building on the master branche ...).

**Comment by pmauduit** [comment]
Then you should have an issue with the cache of your browser, I can confirm it was working when I tried around an hour ago

**Comment by MaxiReglisse** [comment]
you are right, Pierre, clearing the cache solved the problem !!

**Comment by pmauduit** [comment]
In the meantime I'm in the process of having a docker composition up to date on our servers so that it will be easier to test newly created images (no idea when it will be ready though)
