### ISSUE TITLE
GN3 - sync user's org from LDAP

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1846]
Currently defaults to "myorganization"
![screenshot from 2017-12-14 17-08-32](https://user-images.githubusercontent.com/265319/34001888-7f2f5e82-e0f1-11e7-9504-51f886b4fd8a.png)

This information is displayed when using the https://github.com/geonetwork/core-geonetwork/issues/750 feature

**Comment by fvanderbiest** [comment]
This is because of https://github.com/georchestra/datadir/blob/6ae33ae8e65f291a6080b2fe91ea000dfd74858b/geonetwork/geonetwork-security-overrides.properties#L5

@pmauduit do you think we could wire this to the organisation name the user belongs to ?

**Comment by fvanderbiest** [comment]
Or, should we periodically run a task to sync organisation names to the user's o field ?

**Comment by fvanderbiest** [comment]
related issue is #1683

**Comment by pmauduit** [comment]
I guess we could:

* modify this class: https://github.com/georchestra/geonetwork/blob/georchestra-gn3.4-master/core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java to implement something coherent with our LDAP structure in geOrchestra (we are in a GN fork, it is legit to have some modifications in regards to upstream)
or

* use the georchestra-utils module in our fork to override the previous class (https://github.com/georchestra/geonetwork/tree/georchestra-gn3.4-17.12/georchestra-utils) with a custom LDAPSynchronizerJob, so that it would be easier for us to merge upstream modifications in the future. Then we only have to wire the custom class here: https://github.com/georchestra/datadir/blob/6ae33ae8e65f291a6080b2fe91ea000dfd74858b/geonetwork/config/config-security-georchestra.xml#L102-L117

**Comment by fvanderbiest** [comment]
Second option is the most desirable here!

**Comment by pmauduit** [comment]
yes probably,  and in term of dev time, both are quite similar anyway.

**Comment by pmauduit** [comment]
I missed the point in my previous analysis, users are actually updated at login, the previous synchronization does not take care of creating the users in the DB, but removing the users from the DB when they do not exist anymore in the LDAP.

the bean to customize is the following: https://github.com/georchestra/datadir/blob/17.12/geonetwork/config/config-security-georchestra.xml#L76-L101

**Comment by fvanderbiest** [comment]
This will be part of 23.0.0 with the migration to GeoNewtork 4.2 https://github.com/georchestra/georchestra/issues/3706
