### ISSUE TITLE
Check geoserver 2.12 works with extensions

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1856]
eg GeoBretagne uses:
 * colormap
 * mbtiles
 * sldservice
 * spatialite
 * wps-download
 * app-schema
 * control-flow
 * csw
 * feature-pregeneralized
 * gdal
 * geosearch
 * importer
 * inspire
 * libjpeg-turbo
 * monitor
 * ogr-wfs
 * pyramid
 * wps

These extensions should probably be shipped by default in our docker + deb + war builds

**Comment by pmauduit** [comment]
> These extensions should probably be shipped by default in our docker + deb + war builds

I don't agree with this:

* I kept the previous profiles in the pom, activating profiles allows the user to choose whatever he/she wants in the generated webapp at compile-time. Having a "all-in-one" webapp with lots of plugins is not the good way to go IMHO. I'd rather prefer keeping the same webapp base as GS upstream
* We already faced with incompatibilities between GS plugins
* GS is quite good on its own documentation about installing extra plugins, and copying extra jars in the classpath (/WEB-INF/lib) is fairly straightforward

This does not question the fact that these maven profiles should be tested to ensure we have every extra plugins resolved.

**Comment by fvanderbiest** [comment]
Building with -Pdocker,colormap,mbtiles,sldservice,spatialite,wps-download,app-schema,control-flow,csw,feature-pregeneralized,gdal,geosearch,importer,inspire,libjpeg-turbo,monitor,ogr-wfs,pyramid,wps currently results in:

```
[WARNING] The requested profile "mbtiles" could not be activated because it does not exist.
[WARNING] The requested profile "wps-download" could not be activated because it does not exist.
[WARNING] The requested profile "ogr-wfs" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project geoserver-webapp: Could not resolve dependencies for project org.georchestra:geoserver-webapp:war:17.06-SNAPSHOT: The following artifacts could not be resolved: org.geoserver.extension:gs-geosearch:jar:2.12.1, org.geoserver.community:gs-sldservice:jar:2.12.1: Could not find artifact org.geoserver.extension:gs-geosearch:jar:2.12.1 in georchestra (https://packages.georchestra.org/maven/repository) -> [Help 1]
```

**Comment by fvanderbiest** [comment]
Now I could build with colormap,mbtiles,spatialite,wps-download,app-schema,control-flow,csw,feature-pregeneralized,gdal,importer,inspire,libjpeg-turbo,monitor,pyramid,wps

**Comment by fvanderbiest** [comment]
geoserver_1                 | java.lang.UnsatisfiedLinkError: /tmp/jetty/spatialite-3.7.22.4-libspatialitejdbc.so: libgeos_c.so.1: cannot open shared object file: No such file or directory

**Comment by Vampouille** [comment]
> geoserver_1 | java.lang.UnsatisfiedLinkError: /tmp/jetty/spatialite-3.7.22.4-libspatialitejdbc.so: libgeos_c.so.1: cannot open shared object file: No such file or directory
> 
> We'll have to install the native lib, see http://docs.geoserver.org/stable/en/user/community/spatialite/index.html

Should be fixed by https://github.com/georchestra/georchestra/pull/1865

**Comment by fvanderbiest** [comment]
We're still getting this warning on master : 
```
geoserver_1                 | java.lang.UnsatisfiedLinkError: /tmp/jetty/spatialite-3.7.22.4-libspatialitejdbc.so: libproj.so.0: cannot open shared object file: No such file or directory
```

**Comment by fvanderbiest** [comment]
libproj.so.0 was provided by https://packages.debian.org/jessie/amd64/libproj0/filelist on jessie, but there does not seem to an equivalent package for stretch

**Comment by pmauduit** [comment]
> libproj.so.0 was provided by https://packages.debian.org/jessie/amd64/libproj0/filelist on jessie, but there does not seem to an equivalent package for stretch

indeed. The jar spatialite-jdbc-3.7.2-2.4.jar comes with its own native libraries (which is not a good practice btw):

```
native
├── Linux
│   ├── amd64
│   │   ├── libspatialitejdbc.so
│   │   └── libsqlitejdbc.so
│   └── i386
│       ├── libspatialitejdbc.so
│       └── libsqlitejdbc.so
├── Mac
│   ├── i386
│   │   └── libspatialitejdbc.jnilib
│   └── x86_64
│       └── libspatialitejdbc.jnilib
└── Windows
    ├── amd64
    │   └── sqlitejdbc.dll
    └── x86
        └── spatialitejdbc.dll
```

They reference libproj.so.0, which is not provided anymore by any package on stretch as you have seen:

```
% ldd libspatialitejdbc.so                                                                                                                            
	linux-vdso.so.1 =>  (0x00007ffd135b8000)
	libgeos_c.so.1 => /usr/lib/x86_64-linux-gnu/libgeos_c.so.1 (0x00007f432af7f000)
	libproj.so.0 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f432abb5000)
	libgeos-3.5.0.so => /usr/lib/x86_64-linux-gnu/libgeos-3.5.0.so (0x00007f432a81b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f432a499000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f432a283000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f432b496000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4329f7a000)
```

We can try to `ln -s /usr/lib/x86_64-linux-gnu/libproj.so` onto `libproj.so.0`, but there is no guarantee that it won't explode farther (if libproj in the new versions broke some things in its API, we are lost).

Another safer solution could be to take the libproj.so.0 from jessie, since it seems that it is only relying on the the libmath and libc libraries (which are supposed to be stable).

The ideal solution would be to have a more up-to-date jar for spatialite, which does not exist unfortunately, relying on mvnrepository:
http://mvnrepository.com/artifact/org.xerial/spatialite-jdbc/3.7.2-2.4

**Comment by fvanderbiest** [comment]
> The ideal solution would be to have a more up-to-date jar for spatialite

How difficult would it be to build this spatialite-jdbc.jar by ourselves ?

**Comment by pmauduit** [comment]
> How difficult would it be to build this spatialite-jdbc.jar by ourselves ?

There is no fast answer to this, we could have a shot with the following repo: https://github.com/benstadin/spatialite4-jdbc, that we could provide onto the georchestra maven repository, but it will involve maintaining it up to date (hopefully the underlying native libs won't change every months), and fix the versions of it in our maven dependencies whenever it is used, but my main concern here is the use of these libs directly bundled into the jar.

My point is that unless you have a good reason (targeting android apps for example, where apt-getting the missing libraries is not an option), bundling binaries into your jar is not a good practice (you have to guess on which platform you are running, make sure that the libraries can find their dependencies on the host they are running ... too many assumptions that are clearly outside of the project).

If we are looking for a quicker fix, i'd go for my second one (getting the needed libproj.so so that the linker will resolve it, since I'm confident with the fact that libmath and libc are pretty stable across time). At least, with no guarantee that it will solve our issue, this is something that we can try.

**Comment by fvanderbiest** [comment]
OK, let's drop spatiallite for the release, considering the geopackage provider works with 2.12.

**Comment by fvanderbiest** [comment]
Cleaning done with 3ddbdc0987cdbde27861f55198c60469a1ce1987
