### ISSUE TITLE
proxy - duplicated response headers

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2034]
On master, `/console/manager/` HTTP response has duplicated headers:

![capture du 2018-05-04 10-31-36](https://user-images.githubusercontent.com/265319/39618997-72b94eb6-4f86-11e8-849c-e87b88463777.png)

In addition, chromium displays in the console "Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied."

**Comment by pmauduit** [comment]
the duplicated headers are probably copied twice in this code snippet:
https://github.com/georchestra/georchestra/blob/17.12/security-proxy/src/main/java/org/georchestra/security/HeadersManagementStrategy.java#L268-L320

**Comment by pmauduit** [comment]
I replaced the addHeader in the previous code snippet by a setHeader (which replaces the header by the new value instead of adding it twice if already present), but I'm perplexed by the modification:

1. The HTTP spec allows to specify several times the same header
2. The code has not changed for ages, so either something changed in the servlet spec (maybe the HttpResponse now comes with some default headers)
3. what if the response from apache HttpClient contains intentionally the same header several times ? we definitely should transmit them in the same way the SP receives them IMHO.

**Comment by fvanderbiest** [comment]
Note that this was witnessed on a SP running with Jetty/docker tagged `9-jre8` as per
https://github.com/georchestra/georchestra/blob/92f3af8b7c0cf1f8bccf0f5bddabe7d6c6a5c10c/security-proxy/src/docker/Dockerfile#L1

But this is probably not meaningful, since the 9.4 release line is not recent.

**Comment by pmauduit** [comment]
WIP on a better approach on the `fix_sp` branch.

**Comment by fvanderbiest** [comment]
Fixed with #2064 - Thanks !
