### ISSUE TITLE
where is docker-compose.yml ?

### ISSUE THREAD

**Issue by MaxiReglisse** [georchestra/georchestra#2089]
I can not find the file docker-compose.yml, neither in the version master, nor in version 17.12
consequently, the "docker-compose up" command fails : 

    ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?
    Supported filenames: docker-compose.yml, docker-compose.yaml

any help would be appreciated.

**Comment by fvanderbiest** [comment]
It is now located in the georchestra/docker repository.

**Comment by MaxiReglisse** [comment]
sorry, but i can not see it : i only find the docker-compose for the SMTP container.

    [georchestra@Service-Info12 georchestra (master)]$ find docker -name docker-compose.yml
    docker/smtp/docker-compose.yml

**Comment by pmauduit** [comment]
@fvanderbiest meant here: https://github.com/georchestra/docker/blob/master/docker-compose.yml (which is a separated repository in the georchestra organization on github), here is your pizza ;-)

**Comment by MaxiReglisse** [comment]
yeah, i found my pizza ! Thanks.

**Comment by fvanderbiest** [comment]
We decided to move it to a dedicated repository, since we did not want to force people into downloading 3Gb of useless source code to the sole intent of running a composition.
This leaves room for a new composition in the main repository, which would, for instance, be dedicated to development purposes, while https://github.com/georchestra/docker is dedicated to demo or small scale production systems.
