### ISSUE TITLE
GDPR compliance - account default validity duration

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2150]
The console already offers the ability to define an expiration date at user level.
By default, this expiration date is empty.

The current issue is about letting the platform administrator define a default account validity duration.

**Comment by fvanderbiest** [comment]
I do not remember how we came to the conclusion that having expiring accounts leads to a better RGPD conformance... 

Just checked https://gdpr.eu/checklist/

**Comment by severo** [comment]
You're right, it doesn't seem to be directly related. I think that it would be useful only if the user data are deleted after the expiration date, under the principle of minimizing personal data (but I don't know if that principle is directly related to GDPR). Anyway, from a security point of view, it would be a good idea, since it reduces the impact of a potential data leak.
