### ISSUE TITLE
console - support multiple accounts sharing the same email

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2156]
I'm really not sure this is a good idea but let's discuss it here...
First of all: 
 * why would you want such a feature ?
 * where's the technical blocker ?

**Comment by landryb** [comment]
it's not a good idea. definitely.

In many other login systems, the email is the unique key for users.. e.g in drupal you can't create an account with an email that is already linked to an existing account.

What happens when the user requests his password to be reset, and you send the email to a given address ? ask him which account he wants to reset ?

We had the same internal discussion about allowing an user to be linked to several orgs (which is the real life usecase i guess you're trying to solve by allowing multiple accounts per email..), and it turned out to be too painful to handle. Same thing for multiple accounts per email, not worth the added complexity imo.

**Comment by gryckelynck** [comment]
Yes I agree for a strict use of LDAP for geOrchestra users, but we use LDAP for 2 kinds of users:
- active users (wich have active geOrchestra account)
- contacts of GéoGrandEst directory 
What's happend when a contact want to create an account which already exists... ?
Should we continue to manage many lists of contacts in parallel?

**Comment by gryckelynck** [comment]
How do you do to create 9 or 10 tests users (or maybe more).
Do you create email for each one?

**Comment by landryb** [comment]
> active users (wich have active geOrchestra account)
> contacts of GéoGrandEst directory
> What's happend when a contact want to create an account which already exists... ?
> Should we continue to manage many lists of contacts in parallel?

I think with #2108 those two usecases will have to live in distinct LDAP branches anyway. 'contacts' and 'accounts' are two distinct types of LDAP objects.. and it's usually not a good idea to mix distinct notions in a single LDAP branch. As for *managing many lists of contacts in parallel*, imo it's a tooling problem, not a directory structure one..

> How do you do to create 9 or 10 tests users (or maybe more).
> Do you create email for each one?

email aliases in `/etc/mail/aliases` are free :) and anyway, when testing, it's usually simpler to have a local-only domain/mail server that receives everything.

**Comment by fvanderbiest** [comment]
Okay, this is more of an implementation issue for the GGE project rather than a geOrchestra issue.
Closing. Thanks you all for your inputs here !
