### ISSUE TITLE
viewer - allow to deactivate upload formats

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2308]
Currently, in Mapfishapp upload file functionality, all the available formats are proposed to the user:

![captura de pantalla de 2018-12-04 12-14-27](https://user-images.githubusercontent.com/1676121/49455813-2caa3800-f7be-11e8-9ade-2893c053c729.png)

The list depends on the capabilities of the backend service (if GDAL is installed or not).

The proposed enhancement is to allow the administrator to select a subset of formats, eg. "SHP, KML" instead of "SHP, MIF, GML, KML", using something similar to [what was done for the extractor addon](https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/main/webapp/app/addons/extractor/manifest.json#L15):

```json
        "vectorFormatData": [
            ["shp", "Shapefile"],
            ["mif", "Mif/Mid"],
            ["tab", "TAB"],
            ["kml", "KML"]
        ],
```

**Comment by fvanderbiest** [comment]
IIRC, reading files with gdal has been removed on 18.06. We now always use Geotools.
As a result, the purpose of GEOR.config.FILE_FORMAT_LIST is null.

We can remove those lines: https://github.com/georchestra/georchestra/blob/56b8e87b0fc1822416697c2594950934b74f5248/mapfishapp/src/main/webapp/WEB-INF/jsp/index.jsp#L217 and https://github.com/georchestra/georchestra/blob/56b8e87b0fc1822416697c2594950934b74f5248/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/AbstractController.java#L73, and harcode ["shp", "gml", "kml"] instead of  ["shp", "gml", "kml", "mif"] if we decide to not support it anymore (eg because of #256). No need to have an extra config option for this IMO.

This code would be greatly simplified: https://github.com/georchestra/georchestra/blob/56b8e87b0fc1822416697c2594950934b74f5248/mapfishapp/src/main/webapp/app/js/GEOR_fileupload.js#L230-L253

**Comment by severo** [comment]
> IIRC, reading files with gdal has been removed on 18.06. We now always use Geotools.

OK. So, maybe we should remove some code from pom.xml: https://github.com/georchestra/georchestra/blob/18.06/mapfishapp/pom.xml#L162

**Comment by severo** [comment]
>  , and harcode ["shp", "gml", "kml"] instead of  ["shp", "gml", "kml", "mif"] if we decide to not support it anymore (eg because of #256). No need to have an extra config option for this IMO.

There are too options:

- to hardcode there and therefore remove a lot of the code in the https://github.com/georchestra/georchestra/tree/18.06/mapfishapp/src/main/java/org/georchestra/mapfishapp/ws/upload directory that would not be useful anymore, like the [/ws/formats endpoint](http://sdi.georchestra.org/mapfishapp/ws/formats).
- to simply remove mentions of MIF/MID (and also TAB that do not seem to be available anymore)

I think it's better to go for the second option (one commit to remove MIF/MID, another to remove TAB) because:
- maybe people is using the mentioned endpoint
- it could be useful to keep this mechanism for future formats (GeoJSON for example?)

**Comment by severo** [comment]
Remaining (but maybe in another issue, or simply to let as is):

- [ ] remove support for TAB format in upload file functionality
- [ ] remove support for GPX format in upload file functionality
- [ ] remove support for MIF/MID in extractorapp / extractor addon
- [ ] remove dependencies to GDAL

**Comment by severo** [comment]
@fvanderbiest -> https://github.com/georchestra/georchestra/issues/2308#issuecomment-444558552. What do you think?

**Comment by fvanderbiest** [comment]
>  add support for GeoJSON format in upload file functionality?

Not yet

>  remove support for MIF/MID in extractorapp / extractor addon?

Not sure about it. Maybe people are still using it ?

For the rest of the list, you can go for it.
Thanks !

**Comment by severo** [comment]
OK, I will create the corresponding issues
