### ISSUE TITLE
Should we create a branch per milestone?

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2445]
There is a proposal (from a discussion with @groldan and @pmauduit) to:

- work on master for the next milestone (currently 18.12)
- create a dedicated branch for every other milestone (eg 19.06-dev?)

When the next milestone is reached, we:

- create a branch for it (eg 18.12)
- merge the next milestone to master (19.06-dev -> master)
- delete that branch (x 19.06-dev)

The benefits would be to help focusing on the next milestone.

**Comment by groldan** [comment]
That could work.
Additionally, I'd say let's tag the docker images with the release version when a release is made. If 18.12 was released and some time later it needs to be re-published with some patches then create a patch release, 18.12.1, 18.12.2, etc; and tag both in github and docker, so that it's easy to reproduce a bug submitted against a given release either way.

**Comment by fvanderbiest** [comment]
Or we can branch 18.12 from master right now, and:
 * have PRs with new features / possible regressions on master
 * fix things for 18.12 on the 18.12 branch

**Comment by fvanderbiest** [comment]
We now have a [18.12 branch](https://github.com/georchestra/georchestra/tree/18.12) to prepare the release.
