### ISSUE TITLE
Update jetty images to JRE 11

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2489]
There are jetty images running with jre11 see https://hub.docker.com/_/jetty

**Comment by fvanderbiest** [comment]
Will require GeoServer 2.15 at least

**Comment by fvanderbiest** [comment]
Gabriel commented elsewhere "Also make use of the (new in Java 10) -XX:InitialRAMPercentage, -XX:MaxRAMPercentage, and -XX:MinRAMPercentage JVM options to control the heap size relative to the container memory limits"

**Comment by RemiDesgrange** [comment]
Will also allow use to test different GC option. Java 11 has 3 GC (ParrallelGc, G1, ZGC).

**Comment by landryb** [comment]
Fwiw java 11 is the only version supported in debian 10/buster.

**Comment by RemiDesgrange** [comment]
I will update the doc accordingly but I am still clarifiying stuff here:

**java 11 means nothing when it comes to runtime**. 

Java11 is a language specification. It runs on JVM. Since the new release process of Oracle (with JDK9) everything change. We can't talk about java11 when we talk about the runtime, the only runtime we're interest on is OpenJDK. OpenJDK have multiple builds. For example github actions (CI/CD) uses Azul build of OpenJDK. I don't know which build Debian uses. 
Georchestra _should_ run fine on any OpenJDK builds, but since we only test it on Azul+Debian+AdoptOpenJDK one we cannot know in advance.

Jetty docker images are using AdoptOpenJDK: https://github.com/docker-library/openjdk/blob/master/11/jre/Dockerfile#L36

And for the record, relying on debian package for JRE is a ticking bomb...

**Comment by landryb** [comment]
> And for the record, relying on debian package for JRE is a ticking bomb...

can you clarify ? because that's what everyone (not using docker) is doing.

**Comment by RemiDesgrange** [comment]
Two things:

* It happened in the past that Debian broke OpenJDK, without any notice. It took me out of my bed 1 time a 3am. Not doing this mistake again. 
* Debian does not _always_ follow the exact release version. People start noticing when JDK8u212 was released (this update bring cgroup support in the OpenJDK JVM) and some bugs remain on the debian version, because debian maintainer didn't use the same commit (tag)  the release uses. (cannot found the blog post from docker that talks about it).

Still Debian remain a distribution heavily tested and with a huge user base. I'm really not a fan of the release management at debian but here I stop claiming fact and start putting some personal opinion :-)

So for me using debian packages for installing OpenJDK is not really a good idea.

**Comment by pmauduit** [comment]
Anyway, if one need to install openjdk-8 under a debian buster, one can make use of the adoptopenjdk repositories, see the procedure here:
https://adoptopenjdk.net/installation.html#linux-pkg

**Comment by fvanderbiest** [comment]
Related : #2954

**Comment by fvanderbiest** [comment]
> Will require GeoServer 2.15 at least

and GeoNetwork >= 4.0 !
#3051

**Comment by pmauduit** [comment]
About migrating to Java 11, one of our customers had issues with their geoserver & Java 11, and had to bump the commons-lang3 version to 3.8.x instead of 3.7:
https://github.com/georchestra/georchestra/blob/master/pom.xml#L224

Might relate to the following issue: https://github.com/georchestra/georchestra/issues/3107

**Comment by pmauduit** [comment]
Missing a PR to make GN also compatible.

**Comment by pmauduit** [comment]
> Missing a PR to make GN also compatible.

https://github.com/georchestra/geonetwork/pull/191
