### ISSUE TITLE
broken header in cas

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2569]
headerUrl/headerHeight dont have a default value in https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/includes/top.jsp#L47 sam as #2566 @severo ?

**Comment by landryb** [comment]
Oh, and having headerHeight set to 60 in default.properties doesnt propagate to this JSP it seems.. with headerHeight commented out in cas.properties.

**Comment by severo** [comment]
Normally the JSP templates get these placeholders (that coincidentally are named the same as the default properties, but could be named differently) from https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml#L75-L76.

Did you experience a problem with these placeholders?

**Comment by landryb** [comment]
Well, right now the resulting html has 'src=""' and 'height:px' so they have no value. The only spot i've set those is in default.properties... and i see that cas-servlet.xml has no default value for those anyway ?

**Comment by severo** [comment]
Exactly, the logic is to have mandatory properties in default.properties, and not to set a default value for them when they are called.
But something occurs that prevent the JSP to access the properties. I will try to reproduce.

**Comment by landryb** [comment]
Setting headerHeight/headerUrl in cas.properties doesnt seem to propagate either, i still get ```<iframe src="" style="width:100%;height:px;border:none;overflow:hidden;" scrolling="no" frameborder="0"></iframe>``` on the cas login page, ie header not shown at all..

**Comment by landryb** [comment]
I dont think it matters, but we use our own cas theme, ie not `default` but `WEB-INF/view/jsp/craig`, but i see that the `urlBasedViewResolver` in `cas-servlet.xml` seems to properly include that path.

**Comment by severo** [comment]
I reproduce. I'm investigating

**Comment by severo** [comment]
This is the only module that uses ResourceBundleViewResolver, instead of UrlBasedViewResolver (there is a UrlBasedViewResolver bean in CAS, but i's not used). And ResourceBundleViewResolver does not seem to allow passing arguments to the JSP from the context.
First solution: revert the changes in JSP, and get the getProperty() method back in commons module.
Second solution: use the UrlBasedViewResolver instead of ResourceBundleViewResolver.

**Comment by landryb** [comment]
@pmauduit as the resident spring/java expert, any hint ?

**Comment by severo** [comment]
Let's try to replace ResourceBundleViewResolver with UrlBasedViewResolver in CAS

**Comment by severo** [comment]
I thought of two options, but I couldn't make work any of them...

- replace [org.jasig.cas.services.web.ServiceThemeResolver](https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml#L35 by [RegisteredServiceThemeBasedViewResolver](https://static.javadoc.io/org.apereo.cas/cas-server/5.0.0.RC2/org/apereo/cas/services/web/RegisteredServiceThemeBasedViewResolver.html) since it allows to pass attributes (see setStaticVariables in [ThymeleafViewResolver](https://www.thymeleaf.org/apidocs/thymeleaf-spring4/2.0.20/org/thymeleaf/spring4/view/ThymeleafViewResolver.html)). But it requires updating CAS version to 4.1.4 at least, and other problems appear.
- use [org.springframework.web.servlet.view.UrlBasedViewResolver](https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml#L65) to render the views (or some views, for example commenting lines in [default_views.properties](https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/resources/default_views.properties#L22-L23)). Note that it's necessary to add a reference to `urlBasedViewResolver` in the [list of viewResolvers](https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/cas-servlet.xml#L187-L189). It tried, but got an infinite loop of 302 redirections (don't know why, probably linked in some way with the [login flow](https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/login-webflow.xml))

I think I will need some help to keep moving on this issue.

**Comment by landryb** [comment]
As a temporary workaround i've uncommented/set `headerHeight` & `headerUrl` in `cas.properties`... updating CAS is imo a whole different beast and far too late for 18.12 :)

**Comment by severo** [comment]
Hmmm, I don't think it would work either (and I cannot make it work that way). The problem is not between default.properties and cas.properties, but in the ViewResolver. Or did I miss something?

**Comment by landryb** [comment]
Bah, i thought i had it fixed that way, but it seems not. *sigh*.

I also tried putting the default values in `cas-servlet.xml` but that didnt work (ie still empty in generated html)
```
        <entry key="headerHeight" value="${headerHeight:60}" />
        <entry key="headerUrl" value="${headerHeight:/header/}" />
```
and hardcoding the value didnt work either:
```
        <entry key="headerHeight" value="60" />
        <entry key="headerUrl" value="/header/" />
```
so for now the "fix" is to directly modify top.jsp - note that `${instanceName}` isnt propagated either, nor `${consoleContextPath}` & `${publicUrl}`


interestingly, the `${customCssFile}` var is properly replaced; but it's not defined at the same spot (chunk from top.jsp), this one is defined in `./WEB-INF/classes/cas-theme-craig.properties`

```
<spring:theme code="standard.custom.css.file" var="customCssFile" />
<link rel="stylesheet" href="<c:url value="${customCssFile}" />" />
```

@pmauduit need help :)

**Comment by landryb** [comment]
not having `${publicUrl}` propagated means that upon login on the cas, the browser enters an endless loop of redirecting to the same page over and over again because of https://github.com/georchestra/georchestra/blob/18.12/cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casGenericSuccess.jsp#L24 - rather awkward :)

I was pretty sure CAS was previously redirecting to the url the user was at before going to the login page....

**Comment by landryb** [comment]
Successfully tested with 19.04.201904101712~0642fa9 debian packages from the stable buildbot, no deviations from default on `cas.properties`, and props only set in `default.properties`:

- `${headerHeight}` is correctly applied, be it to cas or mapfishapp
- modified `${instanceName}` is correctly applied (seen in <title> on all pages)
- navigating directly to /cas/login & logging in properly redirects to `${publicUrl}` (well `${scheme}://${domainName}` ;)
- clicking on the 'login' link from mfapp or geoserver, logging in properly redirects to the page i was previously on

the **only** strange thing i have here is a 404 on `header/img/logo.png` (ie no condor logo displayed on the left of the header) while `/etc/georchestra/header/logo.png` & `/srv/tomcat/georchestra/webapps/header/img/logo.png` exist and are the same file... but that might be another issue, and anyway not so many ppl use the default header, right ?

kudos to @severo for all the props simplification, and @RemiDesgrange for fixing the final bits ;) for me that was the last real blocker to put 19.04 in production..
