### ISSUE TITLE
geofence - hibernate sequence missing

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2620]
On a fresh env:
```
ERROR JDBCExceptionReporter ERROR: relation "geofence.hibernate_sequence" does not exist
  Position: 17
```
It seems that the JPA automatic creation of db objects does not work. One workaround for now is to create the missing sequence by hand:

```
create sequence geofence.hibernate_sequence;
grant all on geofence.hibernate_sequence to georchestra;
```

**Comment by fvanderbiest** [comment]
Would it make sense to add it to https://github.com/georchestra/georchestra/blob/19.04/postgresql/080-geofence.sql ?

Also, since we emptied the sql file, would it make sense to change option `geofenceEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]` into `update` at https://github.com/georchestra/datadir/blob/b11671d25e3b4f214bad6b82380f342136f87687/geoserver/geofence/geofence-datasource-ovr.properties#L36

**Comment by pmauduit** [comment]
even with hbm2ddl.auto set to update, the tables are recreated after a drop schema  / create  schema / redeploy of GS with geofence enabled, but the sequence is not created unfortunately.

**Comment by fvanderbiest** [comment]
Then, would it make sense to add it to https://github.com/georchestra/georchestra/blob/19.04/postgresql/080-geofence.sql ?

**Comment by pmauduit** [comment]
> would it make sense to add it to https://github.com/georchestra/georchestra/blob/19.04/postgresql/080-geofence.sql ?

I'd say so, but I would also expect that the sequence would be created by hibernate.

**Comment by pmauduit** [comment]
it also seems that hibernate from geofence won't create the sequence if the `hibernate_sequence` already exists in the public schema.
