### ISSUE TITLE
Debian - Setting up the middleware - LDAP

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2717]
Hi everyone,

Trying to install geOrchestra (debian packages), I had an issue when adding new entries at step "geOrchestra users and groups" : I had to add openssh.ldif first (sudo ldapadd -Y EXTERNAL -H ldapi:/// -f openssh.ldif ) in order for the objectClass "sshPublicKey" to be known.
Then, and only then, adding "testadmin" (in georchestra.ldif) works fine, otherwise : ERROR 21, objectClass #5 type unknown or something similar...

**Comment by pmauduit** [comment]
hi @bendeg 

thanks for finding this out, this is due to a recent PR i did (https://github.com/georchestra/georchestra/pull/2713) and ... I forgot to update the documentation related to the LDAP setup.

Since I added my own ssh keys onto the testadmin user in the provided georchestra.ldif sample, of course it becomes necessary to add the schemas provided by the openssh.ldif, before trying to insert this georchestra.ldif file.

Do you care to update the documentation via a pull-request on this file https://github.com/georchestra/georchestra/blob/19.04/docs/setup/openldap.md#the-memberof-overlay ?

**Comment by bendeg** [comment]
1) that would be my very first pull-request, I currently know the very basic about git and github, I'll try
2) you meant this link instead right ? (I mean not the-memborof-overlay, it's the step after)
[](url)https://github.com/georchestra/georchestra/blob/19.04/docs/setup/openldap.md#georchestra-users-and-groups

**Comment by pmauduit** [comment]
> 1. that would be my very first pull-request, I currently know the very basic about git and github, I'll try

thanks ! I'd have added a paragraph to load the schema before the one describing how to load sample users / groups / roles.


> 2. you meant this link instead right ? (I mean not the-memborof-overlay, it's the step after)
>     https://github.com/georchestra/georchestra/blob/19.04/docs/setup/openldap.md#georchestra-users-and-groups

I meant just before this "georchestra-users-and-groups" section
