### ISSUE TITLE
analytics - gh action repeatedly fails to push to docker hub

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2960]
https://github.com/georchestra/georchestra/runs/445592799?check_suite_focus=true
Don't understand why. Issue with rights on the remote repo ?

**Comment by pmauduit** [comment]
There is another bug (see https://github.com/georchestra/georchestra/runs/450405276) due to the fact that the `georchestra/database` docker image now requires a `POSTGRES_PASSWORD` env variable to be set (it does not take a one by default anymore ?)

Even weirder: If I set the env variable according to the docker-maven-plugin doc :

```
+                        <env>
+                          <POSTGRES_PASSWORD>georchestra</POSTGRES_PASSWORD>
+                        </env>
```

It works back, but only if maven is launched from the analytics/ subdir, it is still failing from the base path (like `mvn verify -P-all,analytics,it`).

Also, the root pom is configured to use the version `0.28.0` of the plugin, yet the analytics one asks for `0.31.0`.

**Comment by fvanderbiest** [comment]
Elementary my dear Pierre, isn't it ? ;-)
1bb9f1d4196ca3d087de21c9080faff5349ea80b
