### ISSUE TITLE
actions - remove the need for a M2_SETTINGS_FILE secret

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2985]
https://github.com/georchestra/georchestra/pull/2966/checks failed because forked repositories do not provide the `M2_SETTINGS_FILE` secret.
This file is currently only used to provide a maven proxy. It does not hold any secret.
As such, it should be versioned in the source code, or provided by any other means.

**Comment by pmauduit** [comment]
It might also be interesting to make sure some of the actions are skipped if not run from the "official" repo (i.e. in a fork), like trying to connect onto docker-hub or all the docker push actions:
https://github.community/t5/GitHub-Actions/don-t-run-actions-on-pull-request-from-fork/td-p/45499

about the m2_settings_file variable, I think we could version it without the docker-hub credentials, as we always use "docker push" instead of "mvn docker:push" to push the images onto docker-hub, so the only interesting part remaining into this settings.xml file will be the url to the maven proxy (artifactory on packages.g.o) which is public.
