### ISSUE TITLE
geoserver - enable CORS by default

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3084]
See https://docs.geoserver.org/latest/en/user/production/container.html#enable-cors
Nearly every SDI needs it ... makes sense to have it ON by default I think.

**Comment by landryb** [comment]
in my experience, toggling/uncommenting those bits in web.xml were not enough to enable CORS for geoserver, i ended up doing it in the nginx reverse-proxy:
```
add_header "Access-Control-Allow-Origin" "*";
add_header "Access-Control-Allow-Headers" "Origin, X-Requested-With, Content-Type, Accept";
```

didnt really understood what was wrong, so i'm interested in a solution.

**Comment by RemiDesgrange** [comment]
And when I see the [implementation](https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/jetty-servlets/src/main/java/org/eclipse/jetty/servlets/CrossOriginFilter.java), I cannot see anything about handling OPTIONS request...

**Comment by RemiDesgrange** [comment]
After some investigation:

* To support CORS we need: 
  * preflight support (HTTP OPTIONS request)
  * `Access-Control-*` headers
* It can happen:
  * before georchestra in your apache/nginx/haproxy/traefik/whatever. But some of these software cannot respond to preflight request, because it's not their job.
  * in the security-proxy, by creating a new filter. This could be tricky because you'll want it to be highly configurable (like I accept CORS on geoserver but not on the console)
  * Code it in  every webapp.
