### ISSUE TITLE
console - org edit page is broken

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3221]
Cannot load https://georchestra.mydomain.org/console/account/orgdetails on docker master ... 
The page works, but the link is inactive:
![Capture du 2020-12-09 17-06-30](https://user-images.githubusercontent.com/265319/101654644-0a002900-3a41-11eb-888d-b90f292c8785.png)

**Comment by RemiDesgrange** [comment]
The bug seems to have been introduced when we switched to HTML5 mode. 

* I tried to disable the router in the `StandaloneController`
* I tried to add a `ng-click` action to a function which does `$window.location.href` but we can't back (the "back" button in the browser doesn't work.)

I have no clue how to fix this properly without ugly hack.

**Comment by RemiDesgrange** [comment]
fixed by @jeanpommier in #3224, #3225, #3226 :tada:
