### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by jasmincatic** [georchestra/georchestra#3524]
Can you help me please? I am trying to run geOrchestra on my docker compose. I installed geOrchestra following tutorial on this link  https://github.com/georchestra/docker/blob/master/README.md and I've done everything as it says, but when I open  https://georchestra-127-0-1-1.traefik.me/  it gives me " 404 page not found". What should I do?

**Comment by pmauduit** [comment]
What is the output of a `docker-compose ps` command ? It looks like at least the frontend webserver (traefik) works correctly but something is missing afterwards (the security-proxy or something else). You should have been redirected to the /header/ webapp if you kept the default configuration ; if not, something might have been wrong.

**Comment by jasmincatic** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/73820259/140703380-9c450c42-fc3d-41c2-9541-c793f293e2ed.png)

There is docker-compose ps command output

**Comment by pmauduit** [comment]
the "georchestra-mydomain-org" lets me think that you are not uptodate in regards to the georchestra/docker git repository. Also, I just cloned the master branch of this repository and had no issue launching the docker compo.

Full explanation: we migrated some weeks ago to traefik.me which provides valid certificates for the loopback network interface (127.0.*.1), but you still seem to launch a former version of the compo. From your version though, if you modified your /etc/hosts so that "127.0.0.1" resolves to "georchestra.mydomain.org", you should be able to load the following page: https://georchestra.mydomain.org/header/ (with an alert because of using a self-signed certificate).
