### ISSUE TITLE
doc - geonetwork4 / mapstore2 link

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3546]
Release notes should explain that one has to manually add the following url template
```
https://your.fqdn/mapstore/#?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":[${service.name}],"sources":[${service.url}]}]
```
... in the geonetwork admin interface => "Paramètres" => "Interface utilisateur" => "Visualiseur" => "Le modèle d'URL du visualiseur" and check "Utilisez un visualiseur externe"

Ideally, this should come pre-installed for new setups (via default sql).

**Comment by fvanderbiest** [comment]
As seen in https://github.com/georchestra/geonetwork/pull/184

**Comment by landryb** [comment]
this one bite me **hard**: make sure that the template has the # after `/mapstore/`, eg `https://your.fqdn/mapstore/#?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":[${service.name}],"sources":[${service.url}]}]` otherwise tomcat and the s-p will choke on the url and you'll lose parts of your sanity, if you still had some :)

**Comment by fvanderbiest** [comment]
fixed the above, thanks a lot !
