### ISSUE TITLE
22.0 migration notes

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3547]
To be redacted from https://gist.github.com/pmauduit/c743ac13cc4b08dd4cda150d6279ef16

**Comment by landryb** [comment]
also related : #3511 & #3546

* GN4 bits from #3218 ?
* a section about es/kibana for GN4 cf georchestra/ansible#85 ? 
* a section about datafeeder db scheme ?
* a section about ms2 datadir changes cf https://mapstore2.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210102-to-20210200 and georchestra/datadir#224

**Comment by fvanderbiest** [comment]
Removing my assignment since i'm not able to take over this one

**Comment by pmauduit** [comment]
Required by CAS6:

```
 -DCAS_BANNER_SKIP=true \
        -DCAS_UPDATE_CHECK_ENABLED=true \
        -Dcas.standalone.configurationDirectory=/etc/georchestra/cas/config
```

also tomcat running proxycas now requires openjdk11.

**Comment by landryb** [comment]
requires or can run with jdk11 ?

as for cas6, i didnt have `-DCAS_BANNER_SKIP=true -DCAS_UPDATE_CHECK_ENABLED=true` in my testing setup, what are they for ?

**Comment by pmauduit** [comment]
CAS_BANNER_SKIP is for limiting logging at startup I think, update_check is to avoid having a message "your cas is not uptodate" on the web page IIRC.

**Comment by landryb** [comment]
then maybe it should be false to disable the update check ? :)

**Comment by pmauduit** [comment]
hmmm right :P

**Comment by pmauduit** [comment]
Actually, grepping `CAS_UPDATE_CHECK_ENABLED` into the cas sources, I can't find anything, so I'd say that this one is not needed.

**Comment by pmauduit** [comment]
> requires or can run with jdk11 ?

I think that this is mandatory, doing a rapid try to reconfigure the tomcat-proxycas so that it uses jdk8 shows that:

* the SP still works
* cas is unavailable

**Comment by pmauduit** [comment]
Current state of the migration: after having fixed the sensible default config for docker, I played my functional testsuite against a freshly launched docker composition, and the tests passed fine (incl. a dataset publication via the datafeeder):
https://www.georchestra.org/datadir/reports-docker/index.html

Here are the results for a ansible-based deployment:
https://www.georchestra.org/datadir/reports-vagrant/index.html
(I cheated a bit for this one, because of some glitches with the testsuite, strangely the DF tests pass when launched in non-headless mode, but sometimes fail when headless).

**Comment by pmauduit** [comment]
updated the test reports today (added 2 specs on the console for testing password recovery / account creation):
* https://www.georchestra.org/datadir/reports-docker/index.html
* https://www.georchestra.org/datadir/reports-vagrant/index.html

**Comment by pmauduit** [comment]
PR not merged yet
