### ISSUE TITLE
Removes GN_USERADMIN role

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3548]
GN_USERADMIN was defined in #3399 

To be added to the default LDAP + migration notes + to console's "protected roles" (to prevent deletion)

**Comment by landryb** [comment]
fwiw, since its not fully clear to me, the 'user admin' profile in GN has this rights (per https://geonetwork-opensource.org/manuals/3.10.x/en/administrator-guide/managing-users-and-groups/index.html#users-groups-and-roles):

> User Administrator Profile
> The User Administrator is the administrator of his/her own group with the following privileges:
> *  Full rights on creating new users within the own group
> *  Rights to change users profiles within the own group
> *  Full rights on creating/editing/ deleting new/old data within the own group


in the georchestra context, the first right doesnt make sense, so it boils down to 'the useradmin is able to grant editor/reviewer rights to users in his group and fully manage MD published in his group' ? Did i summarize that right ? will that mean that GN_USERADMIN will be able to grant GN_EDITOR and GN_REVIEWER in the ldap too, as to me the 'profile by group' info is local to geonetwork only ? This really need proper clear documentation :)

so it's a bit like 'delegated admin' for the console ?

**Comment by fvanderbiest** [comment]
I have to admit that it does not seem to fit very well.
I'll ask again @gryckelynck about the original purpose.

**Comment by fvanderbiest** [comment]
"L’objectif initial était de pouvoir déclencher le moissonnage d’un catalogue via l’API (visiblement ce n’est possible que par les admins de groupes dans GN)."

**Comment by fvanderbiest** [comment]
Based on the above, I think we should not advertise this role in the console app. 
It should stay confidential, if not being removed.

**Comment by pmauduit** [comment]
fixed testsuite after having merged PR above.
