### ISSUE TITLE
LDAP backend

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3574]
Reviewing what we have in the repository, it seems we are using the older `hdb` backend for our docker images, while the newer `mdb` is used when installing through debian packages.
see eg https://github.com/georchestra/georchestra/blob/930ab7c30525c85b26de0576a1cfb97454dd174b/ldap/docker-root/docker-entrypoint.d/01-populate#L36

Why not using `mdb` everywhere ? cc @Vampouille

**Comment by fvanderbiest** [comment]
Yep, this is what's recommended indeed.

**Comment by pmauduit** [comment]
https://github.com/georchestra/georchestra/pull/3612

**Comment by jmbourdaret** [comment]
> Reviewing what we have in the repository, it seems we are using the older `hdb` backend for our docker images, while the newer `mdb` is used when installing through debian packages. see eg
> 
> https://github.com/georchestra/georchestra/blob/930ab7c30525c85b26de0576a1cfb97454dd174b/ldap/docker-root/docker-entrypoint.d/01-populate#L36
> 
> Why not using `mdb` everywhere ? cc @Vampouille

see #1498 , looks like some time ago, we had two different LDIF for docker and non-docker installs.

**Comment by pmauduit** [comment]
Funny, but it seems that with the new version (or because of switching to mdb), the cn=admin user still exists but is not queriable. We can still bind onto the LDAP using cn=admin,dc=georchestra,dc=org, but it won't appear in the result of a ldapsearch anymore.
This is why the tests are failing (because a preflight request is made and checks the existence of cn=admin in the tree).

**Comment by pmauduit** [comment]
rebased / testsuite updated, hoping it will pass now.
