### ISSUE TITLE
Broken password recovery after Java 11 upgrade

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3692]
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: javax/activation/DataSource on console/account/passwordRecovery

**Comment by jmbourdaret** [comment]
probably relates to https://github.com/georchestra/georchestra/issues/2953, https://github.com/georchestra/georchestra/pull/2954

To sum it up , Java 11 removed support for a number of libs, which now needs to be explicitly imported.
The SP `pom.xml` was amended to include those.

about the console and this issue, the libs are there, but it still fails somehow.

Note: **also affect user creation !**  , 
in fact _everytime the *mail* subsystem kicks in._

**Comment by landryb** [comment]
that had to happen :) good catch !

**Comment by jmbourdaret** [comment]
PR proposal here https://github.com/georchestra/georchestra/pull/3693
This may be relevant to other images as well.
at least everywhere there is some ***mail*** interactions _and_ image is based on `jetty:9-jre11`.

The reason why adding the needed libs in `pom.xml / dependencies`  has no effect is because the _classpath_ is not the same for embedded lib like the "JavaMail" here.
those classpath are somewhat restricted to `$JETTY_HOME/lib` or nearby, and `$JETTY_BASE/webapp/console/WEB-INF/...` is discarded for these embedded libs.

Java 11 "externalised" a number of libs, so we need to take care of those, like it has already been done for *xml.bind* and now *javax.mail*

**Comment by landryb** [comment]
was the issue witnessed only on docker setups ?

**Comment by pmauduit** [comment]
> was the issue witnessed only on docker setups ?

The password recovery feature is ending up with the following error:
![00000173](https://user-images.githubusercontent.com/594335/159223938-41b6b97b-ab60-4709-b049-2754601a8cad.jpg)

**Comment by pmauduit** [comment]
Currently checking if tomcat/ansible based setups are also affected.

**Comment by pmauduit** [comment]
> Currently checking if tomcat/ansible based setups are also affected.

There are similar errors with tomcat (not exactly the same, but still):

```
	org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in ServletContext resource [/WEB-INF/spring/webmvc-config.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

**Comment by pmauduit** [comment]
> This is caused by the geOrchestra buildbot which still uses java8 for building, we will have to switch to jdk11.

Apart from that, the console debian package is working fine with java11 (once added the missing jaxb jar by hand into the classpath)
