### ISSUE TITLE
GeoNetwork upgrade to 4.2.2

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3706]
Once https://github.com/geonetwork/core-geonetwork/pull/6188 is merged, we hope the GeoNetwork project will publish a new release which we can use for geOrchestra

**Comment by landryb** [comment]
https://geonetwork-opensource.org/manuals/4.0.x/en/overview/change-log/version-4.2.0.html was released. Major bump mostly because of the h2 upgrade, other than that it's mostly the merge of the monster titellus work (cf https://github.com/geonetwork/core-geonetwork/pull/6188) and other bits (cf https://sourceforge.net/p/geonetwork/mailman/message/37654591/) on top of 4.0.6 that we already have.

**Comment by fvanderbiest** [comment]
Yep, we discussed this yesterday with @fgravin @jahow and @tkohr 
Evaluating the risk/opportunity balance before migrating.

Too risky to land on any geOrchestra stable branch. 
Master (= future 22.1.0) looks like a safer choice. Hence we need a `georchestra-gn4-4.2.0` branch in https://github.com/georchestra/geonetwork

**Comment by landryb** [comment]
https://geonetwork-opensource.org/manuals/4.0.x/en/overview/change-log/version-4.2.1.html

**Comment by fvanderbiest** [comment]
4.2.2 brings new abilities, cf https://github.com/etalab/data.gouv.fr/issues/913
