### ISSUE TITLE
Upgrade MapStore from 2021.02.xx to 2022.01.xx

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3713]
geOrchestra `22.0.x` relies on MapStore `2021.02.xx`

With https://github.com/georchestra/mapstore2-georchestra/issues/506 it is planned to have MapStore `2022.01.xx` merged on geOrchestra `master`, which means geOrchestra `22.1.x` should feature MapStore `2022.01.xx` with 3D tiles support.

Migration notes on https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210202-to-20220100

**Comment by landryb** [comment]
technically, since it's a standalone repo, there will be a 2022.01.xx branch in ms2-georchestra repo, and since there's no particular adherence on a particular georchestra/geoserver version, i think ppl will be able to use ms2 2022.01.xx with georchestra 22.0. Ofc, remains to be seen if config files need updating in the datadir (per the migration guide there seems to be few/none).

it's also more a question of whether the community decides to push (for example) an updated 2022.01.xx package in the 22.0 debian package repo/war directory or wait for 22.1 (when it's released).

**Comment by fvanderbiest** [comment]
> remains to be seen if config files need updating in the datadir

Yep, our policy is to offer stable config files on a release branch - which means we won't migrate to mapstore 2022.1 on geOrchestra 22.0

Let's release geOrchestra 22.1 soon, with an updated GeoNetwork version too (after https://github.com/geonetwork/core-geonetwork/pull/6188 a 4.0.7 version should be published IIUC)

**Comment by fvanderbiest** [comment]
Also expecting DataGrandEst to support the migration to GeoServer 2.20.x
