### ISSUE TITLE
atlas - remove from core

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3737]
The atlas module is rarely deployed, and has no client for mapstore.
I suggest we move it to its own repository : georchestra/atlas, preserving commit history.

**Comment by pmauduit** [comment]
> same is true for extractorapp I guess

nothing is planned e.g.mapstore-side to replace the extractorapp addon ? I thought the idea was to be isofunctional before replacing mapfishapp

**Comment by fvanderbiest** [comment]
> nothing is planned e.g.mapstore-side to replace the extractorapp addon ?

Asking @landryb @catmorales ...

**Comment by landryb** [comment]
i don't even know what extractorapp exactly did so .. :)

**Comment by landryb** [comment]
if all extractorapp did was providing the contextual menu with formats to download, then yes mapstore has that:

![image](https://user-images.githubusercontent.com/3421760/166450130-ae014b24-74e9-47be-8ffb-2d1c0d7f0ea2.png)

i've filed an issue because export via WPS didnt work for me (georchestra/mapstore2-georchestra#489) but then ms2 fallbacks to WFS export from GS so it works

**Comment by fvanderbiest** [comment]
Extractorapp allows you to choose which geographic extent to download. 
Not sure MapStore does it ?

**Comment by fvanderbiest** [comment]
Also, it allows you to download not only local layers but also remote layers (as long as remote servers support WFS / WCS)

**Comment by fvanderbiest** [comment]
Atlas exported with its history into https://github.com/georchestra/atlas
