### ISSUE TITLE
datafeeder - missing namespace alias for WFS layer name

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3776]
datafeeder generates metadata XML :
![Capture d’écran du 2022-07-22 14-25-10](https://user-images.githubusercontent.com/265319/180439097-ad969c31-5bd4-4bab-b841-a7f4945e2a2e.png)

WFS link does not work with GeoServer, due to missing namespace alias.

Got : `EPCI_SHAPEFILE`
Expected : `sidi:EPCI_SHAPEFILE`

**Comment by pmauduit** [comment]
> WFS link does not work with GeoServer, due to missing namespace alias.

if the gmd:URL is referencing the workspace, then the namespace is not necessary, geoserver is able to find back the layer name.

**Comment by fvanderbiest** [comment]
> if the gmd:URL is referencing the workspace, then the namespace is not necessary, geoserver is able to find back the layer name.

True with WMS, not true with WFS, to my knowledge.

**Comment by groldan** [comment]
Jesus

**Comment by fvanderbiest** [comment]
@jemacchi did you make progress on this one ? Thanks !

**Comment by jemacchi** [comment]
> @jemacchi did you make progress on this one ? Thanks !
@fvanderbiest 
yes, so far now I'm more familiar with the datafeeder codebase and project itself. 
As result of research, found that at this [class](https://github.com/georchestra/georchestra/blob/536214ffa36237360d47bdd80ca417074f60995c/datafeeder/src/main/java/org/georchestra/datafeeder/service/publish/impl/MetadataRecordProperties.java#L113-L118)  we should be defining the qualifiedName instead of using simply the name, so we can ensure that at the definition of [onlineResource name definition](https://github.com/georchestra/georchestra/blob/b6575a3d3911d86dddd65fc7df6b7512d2f4c9f2/datafeeder/src/main/resources/default_iso_2005_gmd.xsl#L327-L348) we get the namespace included into the name (so WFS will find the layer name)

Now I need to check how to apply those changes to datafeeder.

**Comment by pmauduit** [comment]
If we only consider the "GN to Mapstore" scenario, in order to have a MD inserted with the datafeeder working correctly with WFS, I had to edit the WFS section of the MD, so that:

1. I got rid of the parameters in the URL, e.g. keeping the simplest form possible : "https://.../geoserver/psc/wfs"
2. The layer name is fully qualified (with its namespace)

the 2. was necessary but not sufficient. My concern is "doest it still comply with the way of writing metadatas ?" Or do we also have a bug in the way the URL to Mapstore is constructed ?

**Comment by pmauduit** [comment]
After having discussed via IRC and Slack, it sounds ok to:

1. drop the parameters from the URL
2. fully-qualify the layer name
When the DF creates a MD.

**Comment by pmauduit** [comment]
> fully-qualify the layer name

Does not work for WMS, where Mapstore won't be able to find the layer from the GetCapabilities.

**Comment by pmauduit** [comment]
@jemacchi see above for my first shot on this issue
