### ISSUE TITLE
[geonetwork] configure the externalViewer url template

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3958]
GN 4.x supports configuring an external viewer, like mapstore, to view the WMS/WFS resources.

On page ```/geonetwork/srv/fre/admin.console#/settings/ui```, section "viewer" > "external viewer" > "viewer url pattern"

Depending on the geOrchestra instances, one out of the 2 following URL templates work:

- pattern that should match [GN](https://github.com/geonetwork/core-geonetwork/blob/main/web-ui/src/main/resources/catalog/js/CatController.js#L758) and [mapstore's documentation](https://docs.mapstore.geosolutionsgroup.com/en/v2021.02.02/developer-guide/map-query-parameters/#add-layers):  ```/mapstore/#/?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["${service.name}"],"sources":[{"type":"${service.type}","url":"${service.url}"}]}]```
- pattern actually working for some production instances ```/mapstore/#/?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":[${service.name}],"sources":[${service.url}]}]```

In the second case, it seems that the `${service.url}` block is producing the text content that the first case outputs with `{"type":"${service.type}","url":"${service.url}"}`. Which is confirmed when looking at the URL we get, if we use the first template on an instance that supports the second.

This seems to be due to the `georchestra` view in geonetwork's configuration. I'm particularly suspecting the following code snippet in the geonetwork/catalog/views/georchestra/module.js file: https://github.com/georchestra/geonetwork/blob/georchestra-gn4.2.x/web-ui/src/main/resources/catalog/views/georchestra/module.js#L132-L134

I've checked on the georchestra instances that work with the first template, they are not loading the module.js from the georchestra view (probably not loaded at all). If asking to load the view by adding `?debug&view=georchestra` in the URL, I'm getting the behaviour associated with the instances that support template 2, which seems to confirm my hypothesis.

Which raises at least 2 questions:
- how come some georchestra instances are using the georchestra view, and some the default view ?
- there seem to be some deprecated and broken code in the geonetwork/catalog/views/georchestra/module.js file. Which parts should be removed ?

**Comment by jahow** [comment]
Thanks @jeanpommier, very good find. I was struggling to reproduce this issue but indeed, there's some custom code in the `georchestra` view which makes the behaviour inconsistent.

For your first question, I guess some instances do not use the `georchestra` view because the migration process did not alter the setting that control this. And since this module changes pretty much only this behavior, then it's not really obvious whether it's active or not. This needs to be investigated further because this module is important for implementing custom georchestra logic in GN.

For the 2nd, I feel like we could just remove the custom `gnExternalViewer._commit` implementation because it does not seem to add anything to the original one here: https://github.com/georchestra/geonetwork/blob/georchestra-gn4.2.x/web-ui/src/main/resources/catalog/components/common/map/externalviewer.js

**Comment by jeanpommier** [comment]
Do you know where this setting is set (georchestra view) ? I couldn't find it. I would haver expected `defaultView`  GN setting to be set to georchestra, but it's not, in the instances using it, and breaks the display when I try

**Comment by jahow** [comment]
Made this part of the 23.0 release, @jeanpommier call if you need any help!

**Comment by jeanpommier** [comment]
Thanks @jahow . I think I'm good, watch for a PR today ;o)

**Comment by landryb** [comment]
well .. thanks a lot @jeanpommier for this analysis about the various template urls, this has caused much confusion to @pmauduit and me :)

> This needs to be investigated further because this module is important for implementing custom georchestra logic in GN.

can you elaborate on that ? i've never fully understood what this js module was doing, to me it was mostly for this 'send layer to viewer' logic.. after georchestra/geonetwork#240 to me what's left (`gnSearchSettings.customSelectActions`) is to add the "view layer" button which already exists in standard GN ?

**Comment by jeanpommier** [comment]
I agree, I didn't see much difference when it was activated and when it was not, except for the templateUrl thing

**Comment by jahow** [comment]
IIRC the georchestra module adds a "add all layers from selected records to the viewer" action which is not part of vanilla GN.

I mean this is probably not critical and most people wouldn't even notice that it's missing. My point was more that we normally expect all GN instances in georchestra to use this view, which can be used to implement or override stuff on top of GN. This is useful because then we don't need to touch the code coming from upstream, and in turn avoid nasty merge conflicts.

I'm not even sure whether it's a problem or not to be honest, it just feels a little bit "not future proof".

**Comment by fvanderbiest** [comment]
Awesome that this got a timely answer for the release !
Thank you all for your contributions. 

To conclude with it, this might require an update: https://github.com/georchestra/georchestra/blob/master/migrations/master/README.md#link-to-mapstore and maybe some words on the default GN view to choose (we currently provide https://github.com/georchestra/geonetwork/blob/bffa2fd56012bf29ac53ff9ac10326e32a4b0ec4/web/src/main/webapp/WEB-INF/classes/setup/sql/data/data-db-default.sql#L705)

**Comment by fvanderbiest** [comment]
The correct URL template to link mapstore is provided by https://github.com/georchestra/geonetwork/pull/235/files#diff-3bb14b615963ac1116f161d329bae4132323b6503d4387b02a6f2c46cd883393R1004
