### ISSUE TITLE
server-deploy - geofence seems mandatory

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#772]
It seems GeoFence is now mandatory in server-deploy, but we don't want that (several projects are still using geoserver data security).

/var/cache/deploy/stable/checkout/server-deploy$ ../mvn -Dserver=xxx -Dnon-interactive=true -Pupgrade -P-all,proxy

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Modules deployment 14.06
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.georchestra:geofence-webapp:war:xxx:14.06 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.142s
[INFO] Finished at: Mon Sep 15 16:09:47 CEST 2014
[INFO] Final Memory: 4M/78M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project server-deploy: Could not resolve dependencies for project org.georchestra:server-deploy:pom:14.06: Failure to find org.georchestra:geofence-webapp:war:xxx:14.06 in http://dev.mapfish.org/maven/repository was cached in the local repository, resolution will not be reattempted until the update interval of mapfish has elapsed or updates are forced -> [Help 1]

**Comment by pmauduit** [comment]
The upgrade profile does define geofence as a dependency:

https://github.com/georchestra/georchestra/blob/15.06/server-deploy/pom.xml#L259-L265

Since I do not use server-deploy module, I don't know if removing it from full and upgrade profile is satisfactory. I guess that people using server-deploy to deploy their geofence-enabled georchestra could activate the geofence profile whenever it is needed.

Shall we remove the explicit dependency in case of full | upgrade profile activation ?

**Comment by fvanderbiest** [comment]
> Shall we remove the explicit dependency in case of full | upgrade profile activation ?

I guess so.

**Comment by pmauduit** [comment]
Note: This would force georchestra administrators with geofence activated to explicitely specify the -Pgeofence profile even when activating the full | upgrade profile
