### ISSUE TITLE
geonetwork - csw filtering on metadata type is incorrect

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#854]
Map metadata created with #751 appear in layer search:
![capture du 2014-12-19 11 13 29](https://cloud.githubusercontent.com/assets/265319/5502848/1ebb1f4c-8770-11e4-8183-fbaf48cbb099.png)
They should not...

Additionnally, the md uuid is not correctly guessed, cf the "plus" link.

**Comment by pmauduit** [comment]
If the hierarchyLevel/scopeCode is not present, the metadata is considered as a dataset. But the field is present since some weeks:

https://github.com/georchestra/geonetwork/blob/georchestra-14.12/web/src/main/webapp/xsl/conversion/OGCWMCtoISO19139/OGCWMC-to-ISO19139.xsl#L75

The MDs causing the bug described here have been generated before the scopeCode was set in the XSL stylesheet. Newer context metadatas should not appear anymore int the mapfishapp UI.

**Comment by fvanderbiest** [comment]
Thanks Pierre, this was indeed fixed by you in https://github.com/georchestra/geonetwork/commit/32ce5d002abd7a6d6212cbbc43443cf5d9a58ddf

I've cleaned the older metadata on maps from the sdi.georchestra.org catalog.
