### ISSUE TITLE
mapfishapp: cant reimport exported KML

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#859]
Don't know if this is a dupe of a previous issue, but if you create a vector layer in mapfishapp, export it to KML, then try to reimport it via 'add local file', the import fails

```
2014-12-30 11:31:24 upload [ERROR] It was found the kml version 2.0. There is not binding for this kml versi?n
2014-12-30 11:31:24 upload [ERROR] This file was not recognized as a valid kml format
```

Tested on sdi.georchestra.org and ids.craig.fr/carto (mapfishapp from 201401).
Opening the kml file in qgis and saving it again 'converts' it to kml 2.2, and the new file can be imported into mapfishapp.

**Comment by pmauduit** [comment]
The error in the logs seems related to the pure geotools (i.e. not GDAL/OGR one) implementation of KML. As far as I remember, the current code in mapfishapp adds extra things to circumvent the GeoTools limitations used in the code.

Since there has been some recent changes in the GT code concerning KMLv2 parsing/reading ( https://github.com/geotools/geotools/pull/604/ ), we shall see if a GT upgrade in mapfishapp changes the behaviour observed here. Maybe some "hacks" in geOrchestra code are no longer needed with a newer version of GT in mapfishapp, but hard to say.

**Comment by pmauduit** [comment]
GDAL implementation fails because it provides typenames from the KML file that it actually cannot read, e.g.:

- GeoTools asks for known type names in the uploaded kml via OGR
- OGR returns an array of string containing ["localhost"] (which seems legit relying on the mapfishapp generated KML file):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
  <Folder>
    <name>localhost</name>
    <description>Exported on Thu Apr 09 2015 10:24:19 GMT+0200 (CEST)</description>

```
- GeoTools asks to read features from this typename ("localhost") via OGR
- OGR complains that the "localhost" typename is not found.
 
Maybe it misses the kml XML namespace somewhere to be defined.

Anyway, when the OGR implementation fails, GeoTools is supposed to come as fallback, but it also fails. Still investigating ...

**Comment by pmauduit** [comment]
Version mismatch: we generate KML2.0 documents which are actually compatible with KML2.1 parser implementation, but the current code refuses when `version == 2.0` ; the fix will be available shortly.

**Comment by fvanderbiest** [comment]
There seems to be a client-side issue too with https://github.com/georchestra/openlayers/blob/master/lib/OpenLayers/Format/KML.js#L32-L41 (namespace mismatch 2.0 / 2.2)

The KML files we produce do not pass the http://www.kmlvalidator.com/validate.htm validator

If I change
```xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
```
into
```xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
```
they do pass the test.

**Comment by fvanderbiest** [comment]
With 79f6d45, KML files can be reimported, but styles are not restored, and annotations appear as points (label being a point attribute, it can be fetched with the info tool).

Leaving this issue open, but we've made progress thanks to GeoBretagne support.
