### ISSUE TITLE
geonetwork & extractorapp - issue with a file lock

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#871]
Does anyone know what's going on with this error in catalina.out ?

geonetwork_1 | Jan 11, 2015 9:19:16 PM java.util.prefs.FileSystemPreferences syncWorld
geonetwork_1 | WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
geonetwork_1 | Jan 11, 2015 9:19:46 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
geonetwork_1 | WARNING: Could not lock User prefs.  Unix error code 2.

**Comment by fvanderbiest** [comment]
Every 30 seconds, the same message is printed in catalina.out ...

**Comment by fvanderbiest** [comment]
Related discussion http://stackoverflow.com/questions/2027566/java-util-prefs-throwing-backingstoreexception-why

**Comment by fvanderbiest** [comment]
@fxprunayre : any idea ?

**Comment by fxprunayre** [comment]
Not really, but maybe it's related to the geotools epsg database created on startup ?

**Comment by fvanderbiest** [comment]
You mean this kind of thing : /tmp/tomcat6-tomcat6-tmp/Geotools/Databases/HSQL/v7.9.0/EPSG.data
hmmm

**Comment by fvanderbiest** [comment]
I found this very interesting reference: http://allaboutbalance.com/articles/disableprefs/

**Comment by fvanderbiest** [comment]
There are also these warnings:

geonetwork_1   | Jan 13, 2015 9:00:57 PM java.util.prefs.FileSystemPreferences$1 run
geonetwork_1   | WARNING: Couldn't create user preferences directory. User preferences are unusable.
geonetwork_1   | Jan 13, 2015 9:00:57 PM java.util.prefs.FileSystemPreferences$1 run
geonetwork_1   | WARNING: java.io.IOException: No such file or directory

**Comment by landryb** [comment]
I've already seen that issue ages ago, i *think* that's because tomcat tries to write to /etc/tomcat6/userPrefs/ and/or systemPrefs/. I solved it by munging JAVA_OPTS to point java.util.prefs.userRoot/java.util.prefs.systemRoot to dirs where tomcat could write.

By default on debian tomcat cant create files/dirs in /etc/tomcat6 which is root:root, so either pre-create the files/dirs with
```
/etc/tomcat6 #install -d -o tomcat6 systemPrefs userPrefs
```

or just put them in tomcat's /temp dir
```
# modif JAVA_OPTS
        -Djava.util.prefs.userRoot=../temp/userPrefs \
        -Djava.util.prefs.systemRoot=../temp/systemPrefs \
```

Then you'll see a .java dir created. I'm not 100% sure that's the issue here, but that quieted the warning for me.

**Comment by pmauduit** [comment]
@landry I guess you're right, and if I understand correctly the `java.util.prefs.syncInterval`, changing it to a very large value may not be a good way to fix the current problem, if you imagine the following scenario:

- A java code opens a file for writing (let's say geotools for internal needs)
- Writes some things into it
- does not close nor explicitely flush
- another piece of code (which might be in another thread) assumes the file has been written, some time < java.util.prefs.syncInterval afterwards

=> file does not exist yet because the sync() performed by the JVM has not arisen yet.

**Comment by fvanderbiest** [comment]
> changing java.util.prefs.syncInterval to a very large value may not be a good way to fix the current problem

True. That's just a quick fix for the docker stack, waiting for a better solution. 
https://github.com/georchestra/docker/commit/395e21a0e10942c178c50e4d91e5a5b86938c483

What Landry proposes is a good solution, and the link I provided before (http://allaboutbalance.com/articles/disableprefs/) has an even better solution: overriding java.util.prefs.PreferencesFactory with a DisabledPreferencesFactory

**Comment by fvanderbiest** [comment]
Same issue with extractorapp:

extractorapp_1 | Jan 17, 2015 8:49:50 PM java.util.prefs.FileSystemPreferences$1 run
extractorapp_1 | WARNING: Couldn't create user preferences directory. User preferences are unusable.
extractorapp_1 | Jan 17, 2015 8:49:50 PM java.util.prefs.FileSystemPreferences$1 run
extractorapp_1 | WARNING: java.io.IOException: No such file or directory

**Comment by fvanderbiest** [comment]
Still the same issue in extractorapp container logs... annoying.

**Comment by fvanderbiest** [comment]
Extractorapp docker is now correctly configured https://github.com/georchestra/georchestra/blob/master/extractorapp/src/docker/Dockerfile

Closing.
