### ISSUE TITLE
geoserver - jsessionid in URL

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#878]
Since the 2.5.4 upgrade, we now have a jsessionid parameter in the urls, eg with
https://vm-georchestra/geoserver/web/;jsessionid=F7B9B0CFEC4FC8D1BD1579C97C5082B5?wicket:bookmarkablePage=:org.geoserver.web.data.store.StorePage

Is it required ? can it be removed ?

**Comment by fvanderbiest** [comment]
Is it linked with the ```rememberme``` filter https://github.com/georchestra/geoserver_minimal_datadir/blob/master/security/config.xml#L11 ?

Isn't it useless, as Fabrice already pointed ?

**Comment by fvanderbiest** [comment]
The rememberme filter was introduced by https://github.com/georchestra/geoserver_minimal_datadir/commit/674342aba61f8fd04e11e75e4eb8a79a7983c61f

**Comment by fvanderbiest** [comment]
Using my docker stack, I just removed the rememberme filter, but the jessionid parameter is still introduced when browsing geoserver admin.

Is it the same behavior when using a standard, non-georchestra, geoserver 2.5.4 instance ?

**Comment by fphg** [comment]
according to this : http://docs.geoserver.org/latest/en/user/security/auth/web.html
Remember Me—Handles “Remember Me” authentication, reading when the flag is set on a form login, creating the appropriate cookie, and recognizing the cookie on future requests

=> imho not the same. rememberme handles authentication and should be useless since secproxy also remembers; jsession handles object persistency between admin pages

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/geoserver/pull/17
