### ISSUE TITLE
mapfish-print: Sources are not easy to find

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#985]
Currently mapfishapp pom targets a jar version that is downloaded and added to the webapp:

https://github.com/georchestra/georchestra/blob/14.12/mapfishapp/pom.xml#L96

It will be interesting to fork the mapfish-print code into its own repository in the georchestra organization, and put the tag onto the correct commit: for now on, both tags (1.2-GEORCHESTRA and 1.2.1-GEORCHESTRA) do not match the commit which allows the print-lib jar compilation currently used.

The supposedly correct commit is the following one:
https://github.com/mapfish/mapfish-print/commit/c15848ab1e4084f7d94fe3a2c17e01fdcf580509

**Comment by fvanderbiest** [comment]
See also branch https://github.com/mapfish/mapfish-print/tree/1.2.x-GEORCHESTRA

**Comment by fvanderbiest** [comment]
We might need to upgrade or patch the branch in order to have the `geodetic` param, described in http://www.mapfish.org/doc/print/protocol.html#print-pdf

This should allow us to fix #1084 by adding the `geodetic` parameter into https://github.com/georchestra/georchestra/blob/15.12/mapfishapp/src/main/webapp/app/js/GEOR_print.js

**Comment by pmauduit** [comment]
The actual commit is the following in the mfprint repository: daeea96d2d3b33d6ccf02fe62d81b9c7aa2574a2

**Comment by fvanderbiest** [comment]
https://github.com/mapfish/mapfish-print/commit/daeea96d2d3b33d6ccf02fe62d81b9c7aa2574a2 in branch 2.x
